// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (value.constructor !== Object && !Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _extrasOk7(_obj4: Record<string, unknown>): boolean {
    let _count5 = 0;
    for (const _k6 in _obj4) {
        _count5++;
    }
    return _count5 <= 1;
}

function _shapeArray10(_arr8: unknown[]): boolean {
    for (let _i9 = 0; _i9 < _arr8.length; _i9++) {
        const _el1 = _arr8[_i9];
        if (!(isPlainObject(_el1) && (typeof (_el1 as Record<PropertyKey, unknown>)["id"] === "number" && !(Number.isNaN((_el1 as Record<PropertyKey, unknown>)["id"]))) && _extrasOk7(_el1 as Record<PropertyKey, unknown>))) {
            return false;
        }
    }
    return true;
}

function _objectIssues22(_val14: unknown): TreeNode | undefined {
    let _issue15: TreeNode | undefined;
    if (!(isPlainObject(_val14))) {
        _issue15 = addIssue(_issue15, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" });
    }
    else {
        let _issue16: TreeNode | undefined;
        let _value17: unknown;
        const _has18 = "id" in _val14;
        if (_has18) {
            _value17 = (_val14 as Record<PropertyKey, unknown>)["id"];
            if (!(typeof _value17 === "number" && !(Number.isNaN(_value17)))) {
                _issue16 = addIssue(_issue16, { type: "nest", key: "id", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
        }
        if (!(_has18)) {
            _issue16 = addIssue(_issue16, { type: "nest", key: "id", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
        let _count20 = 0;
        for (const _k21 in _val14) {
            _count20++;
        }
        if (_count20 !== 1 || !(_has18)) {
            for (const _key19 in _val14) {
                if (!(_key19 === "id")) {
                    _issue16 = addIssue(_issue16, { type: "nest", key: _key19, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
                }
            }
        }
        if (_issue16 !== undefined) {
            _issue15 = addIssue(_issue15, _issue16);
        }
    }
    return _issue15;
}

function _slowArrayObject(value: unknown): ParseResult<{
    "id": number;
}[]> {
    {
        if (!(Array.isArray(value))) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" });
        }
        let _issue11: TreeNode | undefined;
        for (let _index12 = 0; _index12 < value.length; _index12++) {
            let _element13 = value[_index12];
            const _childIssue23 = _objectIssues22(_element13);
            if (_childIssue23 !== undefined) {
                _issue11 = addIssue(_issue11, { type: "nest", key: _index12, child: _childIssue23 });
            }
        }
        if (_issue11 !== undefined) {
            return new ParseErrorResult(_issue11);
        }
        return { ok: true as const, value: value as {
                "id": number;
            }[] };
    }
    return { ok: true as const, value: value as {
            "id": number;
        }[] };
}

export function safeParseArrayObject(value: unknown): ParseResult<{
    "id": number;
}[]> {
    if (Array.isArray(value) && _shapeArray10(value)) {
        return { ok: true as const, value: value as {
                "id": number;
            }[] };
    }
    return _slowArrayObject(value);
}

export function parseArrayObject(value: unknown): {
    "id": number;
}[] {
    const result = safeParseArrayObject(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
