// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _extrasOk7(_obj4: Record<string, unknown>): boolean {
    let _count5 = 0;
    for (const _k6 in _obj4) {
        _count5++;
    }
    return _count5 <= 1;
}

function _shapeArray10(_arr8: unknown[]): boolean {
    for (let _i9 = 0; _i9 < _arr8.length; _i9++) {
        const _el1 = _arr8[_i9];
        if (!(isPlainObject(_el1) && (typeof (_el1 as Record<PropertyKey, unknown>)["id"] === "number" && !(Number.isNaN((_el1 as Record<PropertyKey, unknown>)["id"]))) && _extrasOk7(_el1 as Record<PropertyKey, unknown>))) {
            return false;
        }
    }
    return true;
}

function _objectIssues22(_val14: unknown): TreeNode | undefined {
    let _issue15: TreeNode | undefined;
    if (!(isPlainObject(_val14))) {
        _issue15 = addIssue(_issue15, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" });
    }
    else {
        let _issue16: TreeNode | undefined;
        let _value17: unknown;
        const _has18 = "id" in _val14;
        if (_has18) {
            _value17 = (_val14 as Record<PropertyKey, unknown>)["id"];
            if (!(typeof _value17 === "number" && !(Number.isNaN(_value17)))) {
                _issue16 = addIssue(_issue16, { type: "nest", key: "id", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
        }
        if (!(_has18)) {
            _issue16 = addIssue(_issue16, { type: "nest", key: "id", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
        let _count20 = 0;
        for (const _k21 in _val14) {
            _count20++;
        }
        if (_count20 !== 1 || !(_has18)) {
            for (const _key19 in _val14) {
                if (!(_key19 === "id")) {
                    _issue16 = addIssue(_issue16, { type: "nest", key: _key19, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
                }
            }
        }
        if (_issue16 !== undefined) {
            _issue15 = addIssue(_issue15, _issue16);
        }
    }
    return _issue15;
}

function _slowArrayObject(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "id": number;
}[]> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(Array.isArray(value))) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" };
        }
        let _issue11: TreeNode | undefined;
        for (let _index12 = 0; _index12 < value.length; _index12++) {
            let _element13 = value[_index12];
            const _childIssue23 = _objectIssues22(_element13);
            if (_childIssue23 !== undefined) {
                _issue11 = addIssue(_issue11, { type: "nest", key: _index12, child: _childIssue23 });
            }
        }
        if (_issue11 !== undefined) {
            return _issue11;
        }
        return undefined;
    }
    return undefined;
}

function _validateArrayObject(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "id": number;
}[]> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (Array.isArray(value) && _shapeArray10(value)) {
        return undefined;
    }
    return _slowArrayObject(value, options);
}

function safeParseArrayObject(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<{
    "id": number;
}[]> {
    const result = _validateArrayObject(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "id": number;
            }[] };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseArrayObject(value: unknown, options?: {
    maxDepth?: number;
}): {
    "id": number;
}[] {
    const result = safeParseArrayObject(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "id": number;
}[]> & {
    safeParse: typeof safeParseArrayObject;
    parse: typeof parseArrayObject;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, {
        "id": number;
    }[]>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateArrayObject(value);
            if (result === undefined) {
                return { value: value as {
                        "id": number;
                    }[] };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: {
                            "id": number;
                        }[];
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseArrayObject,
    parse: parseArrayObject
};

export { _schema as ArrayObject };
