// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

function _shapeArray6(_arr4: unknown[]): boolean {
    for (let _i5 = 0; _i5 < _arr4.length; _i5++) {
        const _el1 = _arr4[_i5];
        if (!(typeof _el1 === "string")) {
            return false;
        }
    }
    return true;
}

function _slowArrayString(value: unknown): ParseResult<string[]> {
    {
        if (!(Array.isArray(value))) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" });
        }
        let _issue7: TreeNode | undefined;
        for (let _index8 = 0; _index8 < value.length; _index8++) {
            let _element9 = value[_index8];
            if (!(typeof _element9 === "string")) {
                _issue7 = addIssue(_issue7, { type: "nest", key: _index8, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
        }
        if (_issue7 !== undefined) {
            return new ParseErrorResult(_issue7);
        }
        return { ok: true as const, value: value as string[] };
    }
    return { ok: true as const, value: value as string[] };
}

export function safeParseArrayString(value: unknown): ParseResult<string[]> {
    if (Array.isArray(value) && _shapeArray6(value)) {
        return { ok: true as const, value: value as string[] };
    }
    return _slowArrayString(value);
}

export function parseArrayString(value: unknown): string[] {
    const result = safeParseArrayString(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
