// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _shapeArray6(_arr4: unknown[]): boolean {
    for (let _i5 = 0; _i5 < _arr4.length; _i5++) {
        const _el1 = _arr4[_i5];
        if (!(typeof _el1 === "string")) {
            return false;
        }
    }
    return true;
}

function _slowArrayString(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string[]> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(Array.isArray(value))) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" };
        }
        let _issue7: TreeNode | undefined;
        for (let _index8 = 0; _index8 < value.length; _index8++) {
            let _element9 = value[_index8];
            if (!(typeof _element9 === "string")) {
                _issue7 = addIssue(_issue7, { type: "nest", key: _index8, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
        }
        if (_issue7 !== undefined) {
            return _issue7;
        }
        return undefined;
    }
    return undefined;
}

function _validateArrayString(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string[]> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (Array.isArray(value) && _shapeArray6(value)) {
        return undefined;
    }
    return _slowArrayString(value, options);
}

function safeParseArrayString(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<string[]> {
    const result = _validateArrayString(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as string[] };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseArrayString(value: unknown, options?: {
    maxDepth?: number;
}): string[] {
    const result = safeParseArrayString(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string[]> & {
    safeParse: typeof safeParseArrayString;
    parse: typeof parseArrayString;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, string[]>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateArrayString(value);
            if (result === undefined) {
                return { value: value as string[] };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: string[];
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseArrayString,
    parse: parseArrayString
};

export { _schema as ArrayString };
