// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateBigint(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<bigint> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(typeof value === "bigint")) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "bigint" };
        }
    }
    return undefined;
}

function safeParseBigint(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<bigint> {
    const result = _validateBigint(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as bigint };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseBigint(value: unknown, options?: {
    maxDepth?: number;
}): bigint {
    const result = safeParseBigint(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, bigint> & {
    safeParse: typeof safeParseBigint;
    parse: typeof parseBigint;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, bigint>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateBigint(value);
            if (result === undefined) {
                return { value: value as bigint };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: bigint;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseBigint,
    parse: parseBigint
};

export { _schema as Bigint };
