// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseBigint(value: unknown): ParseResult<bigint> {
    {
        if (!(typeof value === "bigint")) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "bigint" });
        }
    }
    return { ok: true as const, value: value as bigint };
}

export function parseBigint(value: unknown): bigint {
    const result = safeParseBigint(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
