// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateBoolean(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<boolean> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(typeof value === "boolean")) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "boolean" };
    }
    return undefined;
}

function safeParseBoolean(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<boolean> {
    const result = _validateBoolean(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as boolean };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseBoolean(value: unknown, options?: {
    maxDepth?: number;
}): boolean {
    const result = safeParseBoolean(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, boolean> & {
    safeParse: typeof safeParseBoolean;
    parse: typeof parseBoolean;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, boolean>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateBoolean(value);
            if (result === undefined) {
                return { value: value as boolean };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: boolean;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseBoolean,
    parse: parseBoolean
};

export { _schema as Boolean };
