// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseBoolean(value: unknown): ParseResult<boolean> {
    if (!(typeof value === "boolean")) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "boolean" });
    }
    return { ok: true as const, value: value as boolean };
}

export function parseBoolean(value: unknown): boolean {
    const result = safeParseBoolean(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
