// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _chain1: (value: string) => ParseResult<number> = (value) => ({
    ok: true,
    value: Number(value)
});

function _validateChain(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<number> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    let _chainIssue2: TreeNode | undefined;
    let _chainFromValue4: unknown = value;
    if (!(typeof _chainFromValue4 === "string")) {
        _chainIssue2 = addIssue(_chainIssue2, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
    }
    else {
    }
    if (_chainIssue2 !== undefined) {
        return _chainIssue2;
    }
    else {
        let _chainResult3 = _chain1(_chainFromValue4 as string);
        if (!(_chainResult3.ok)) {
            return _chainResult3.issue;
        }
        else {
            let _chainToValue5 = _chainResult3.value;
            if (!(typeof _chainToValue5 === "number" && !(Number.isNaN(_chainToValue5)))) {
                _chainIssue2 = addIssue(_chainIssue2, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
            }
            else {
            }
            if (_chainIssue2 !== undefined) {
                return _chainIssue2;
            }
            else {
                return { ok: true as const, value: _chainToValue5 as number };
            }
        }
    }
    return undefined;
}

function safeParseChain(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<number> {
    const result = _validateChain(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as number };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseChain(value: unknown, options?: {
    maxDepth?: number;
}): number {
    const result = safeParseChain(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, number> & {
    safeParse: typeof safeParseChain;
    parse: typeof parseChain;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, number>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateChain(value);
            if (result === undefined) {
                return { value: value as number };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: number;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseChain,
    parse: parseChain
};

export { _schema as Chain };
