// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

const _chain1: (value: string) => ParseResult<number> = (value) => ({
    ok: true,
    value: Number(value)
});

export function safeParseChain(value: unknown): ParseResult<number> {
    let _chainIssue2: TreeNode | undefined;
    let _chainFromValue4: unknown = value;
    if (!(typeof _chainFromValue4 === "string")) {
        _chainIssue2 = addIssue(_chainIssue2, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
    }
    else {
    }
    if (_chainIssue2 !== undefined) {
        return new ParseErrorResult(_chainIssue2);
    }
    else {
        let _chainResult3 = _chain1(_chainFromValue4 as string);
        if (!(_chainResult3.ok)) {
            return new ParseErrorResult(_chainResult3.issue);
        }
        else {
            let _chainToValue5 = _chainResult3.value;
            if (!(typeof _chainToValue5 === "number" && !(Number.isNaN(_chainToValue5)))) {
                _chainIssue2 = addIssue(_chainIssue2, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
            }
            else {
            }
            if (_chainIssue2 !== undefined) {
                return new ParseErrorResult(_chainIssue2);
            }
            else {
                return { ok: true as const, value: _chainToValue5 as number };
            }
        }
    }
    return { ok: true as const, value: value as number };
}

export function parseChain(value: unknown): number {
    const result = safeParseChain(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
