// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseDate(value: unknown): ParseResult<Date> {
    {
        if (!(value instanceof Date)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Date" });
        }
        const _time1 = value.getTime();
        if (Number.isNaN(_time1)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_DATE });
        }
    }
    return { ok: true as const, value: value as Date };
}

export function parseDate(value: unknown): Date {
    const result = safeParseDate(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
