// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateDate(value: unknown): InternalParseResult<Date> {
    {
        if (!(value instanceof Date)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Date" };
        }
        const _time1 = value.getTime();
        if (Number.isNaN(_time1)) {
            return { type: "leaf", code: issueCodes.INVALID_DATE };
        }
    }
    return undefined;
}

function safeParseDate(value: unknown): ParseResult<Date> {
    const result = _validateDate(value);
    if (result === undefined) {
        return { ok: true as const, value: value as Date };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseDate(value: unknown): Date {
    const result = safeParseDate(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Date> & {
    safeParse: typeof safeParseDate;
    parse: typeof parseDate;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseDate(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseDate,
    parse: parseDate
};

export { _schema as Date };
