// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

const _default0 = deepFreeze(structuredClone("x"));

export function safeParseDefault(value: unknown): ParseResult<Exclude<string, undefined>> {
    if (value === undefined) {
        return { ok: true as const, value: _default0 as Exclude<string, undefined> };
    }
    {
        if (!(typeof value === "string")) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
        }
    }
    return { ok: true as const, value: value as Exclude<string, undefined> };
}

export function parseDefault(value: unknown): Exclude<string, undefined> {
    const result = safeParseDefault(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
