// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

const _default0 = deepFreeze(structuredClone("x"));

function _validateDefault(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value === undefined) {
        return { ok: true as const, value: _default0 as string };
    }
    {
        if (!(typeof value === "string")) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" };
        }
    }
    return undefined;
}

function safeParseDefault(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<string> {
    const result = _validateDefault(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as string };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseDefault(value: unknown, options?: {
    maxDepth?: number;
}): string {
    const result = safeParseDefault(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string> & {
    safeParse: typeof safeParseDefault;
    parse: typeof parseDefault;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseDefault(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseDefault,
    parse: parseDefault
};

export { _schema as Default };
