// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

const _default0 = deepFreeze(structuredClone("x"));

function _validateDefaultUnionUndefined(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string | undefined> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value === undefined) {
        return { ok: true as const, value: _default0 as string | undefined };
    }
    if (typeof value === "string" || value === undefined) {
        return undefined;
    }
    {
        let _success1 = false;
        let _issue2: TreeNode | undefined;
        if (!(_success1)) {
            {
                let _memberIssue3: TreeNode | undefined;
                if (!(typeof value === "string")) {
                    _memberIssue3 = addIssue(_memberIssue3, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
                }
                else {
                }
                if (_memberIssue3 === undefined) {
                    _success1 = true;
                }
                else {
                    _issue2 = addIssue(_issue2, _memberIssue3);
                }
            }
        }
        if (!(_success1)) {
            {
                let _memberIssue4: TreeNode | undefined;
                if (!(value === undefined)) {
                    _memberIssue4 = addIssue(_memberIssue4, { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "undefined" });
                }
                if (_memberIssue4 === undefined) {
                    _success1 = true;
                }
                else {
                    _issue2 = addIssue(_issue2, _memberIssue4);
                }
            }
        }
        if (_success1) {
            return undefined;
        }
        else {
            return _issue2!;
        }
    }
    return undefined;
}

function safeParseDefaultUnionUndefined(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<string | undefined> {
    const result = _validateDefaultUnionUndefined(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as string | undefined };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseDefaultUnionUndefined(value: unknown, options?: {
    maxDepth?: number;
}): string | undefined {
    const result = safeParseDefaultUnionUndefined(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string | undefined> & {
    safeParse: typeof safeParseDefaultUnionUndefined;
    parse: typeof parseDefaultUnionUndefined;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseDefaultUnionUndefined(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseDefaultUnionUndefined,
    parse: parseDefaultUnionUndefined
};

export { _schema as DefaultUnionUndefined };
