// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateDuration(value: unknown): InternalParseResult<Temporal.Duration> {
    if (!(value instanceof Temporal.Duration)) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.Duration" };
    }
    return undefined;
}

function safeParseDuration(value: unknown): ParseResult<Temporal.Duration> {
    const result = _validateDuration(value);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.Duration };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseDuration(value: unknown): Temporal.Duration {
    const result = safeParseDuration(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.Duration> & {
    safeParse: typeof safeParseDuration;
    parse: typeof parseDuration;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseDuration(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseDuration,
    parse: parseDuration
};

export { _schema as Duration };
