// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseDuration(value: unknown): ParseResult<Temporal.Duration> {
    if (!(value instanceof Temporal.Duration)) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.Duration" });
    }
    return { ok: true as const, value: value as Temporal.Duration };
}

export function parseDuration(value: unknown): Temporal.Duration {
    const result = safeParseDuration(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
