// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _enum1 = new Set<unknown>(["a", "b", "c"]);

function _validateEnumString(value: unknown): InternalParseResult<"a" | "b" | "c"> {
    if (!(_enum1.has(value))) {
        return { type: "leaf", code: issueCodes.INVALID_ENUM_VALUE, expected: ["'a'", "'b'", "'c'"] };
    }
    return undefined;
}

function safeParseEnumString(value: unknown): ParseResult<"a" | "b" | "c"> {
    const result = _validateEnumString(value);
    if (result === undefined) {
        return { ok: true as const, value: value as "a" | "b" | "c" };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseEnumString(value: unknown): "a" | "b" | "c" {
    const result = safeParseEnumString(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, "a" | "b" | "c"> & {
    safeParse: typeof safeParseEnumString;
    parse: typeof parseEnumString;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseEnumString(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseEnumString,
    parse: parseEnumString
};

export { _schema as EnumString };
