// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _enum1 = new Set<unknown>([1, 2, 3]);

function _validateEnumNumber(value: unknown): InternalParseResult<1 | 2 | 3> {
    if (!(_enum1.has(value))) {
        return { type: "leaf", code: issueCodes.INVALID_ENUM_VALUE, expected: ["1", "2", "3"] };
    }
    return undefined;
}

function safeParseEnumNumber(value: unknown): ParseResult<1 | 2 | 3> {
    const result = _validateEnumNumber(value);
    if (result === undefined) {
        return { ok: true as const, value: value as 1 | 2 | 3 };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseEnumNumber(value: unknown): 1 | 2 | 3 {
    const result = safeParseEnumNumber(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, 1 | 2 | 3> & {
    safeParse: typeof safeParseEnumNumber;
    parse: typeof parseEnumNumber;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseEnumNumber(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseEnumNumber,
    parse: parseEnumNumber
};

export { _schema as EnumNumber };
