// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

const _enum1 = new Set<unknown>([1, 2, 3]);

export function safeParseEnumNumber(value: unknown): ParseResult<1 | 2 | 3> {
    if (!(_enum1.has(value))) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_ENUM_VALUE, expected: ["1", "2", "3"] });
    }
    return { ok: true as const, value: value as 1 | 2 | 3 };
}

export function parseEnumNumber(value: unknown): 1 | 2 | 3 {
    const result = safeParseEnumNumber(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
