// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateInstant(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.Instant> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Temporal.Instant)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.Instant" };
        }
    }
    return undefined;
}

function safeParseInstant(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.Instant> {
    const result = _validateInstant(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.Instant };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseInstant(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.Instant {
    const result = safeParseInstant(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.Instant> & {
    safeParse: typeof safeParseInstant;
    parse: typeof parseInstant;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, Temporal.Instant>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateInstant(value);
            if (result === undefined) {
                return { value: value as Temporal.Instant };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: Temporal.Instant;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseInstant,
    parse: parseInstant
};

export { _schema as Instant };
