// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateInstant(value: unknown): InternalParseResult<Temporal.Instant> {
    {
        if (!(value instanceof Temporal.Instant)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.Instant" };
        }
    }
    return undefined;
}

function safeParseInstant(value: unknown): ParseResult<Temporal.Instant> {
    const result = _validateInstant(value);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.Instant };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseInstant(value: unknown): Temporal.Instant {
    const result = safeParseInstant(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.Instant> & {
    safeParse: typeof safeParseInstant;
    parse: typeof parseInstant;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseInstant(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseInstant,
    parse: parseInstant
};

export { _schema as Instant };
