// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseInstant(value: unknown): ParseResult<Temporal.Instant> {
    {
        if (!(value instanceof Temporal.Instant)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.Instant" });
        }
    }
    return { ok: true as const, value: value as Temporal.Instant };
}

export function parseInstant(value: unknown): Temporal.Instant {
    const result = safeParseInstant(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
