// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

type _lazy_0Type = {
    "value": string;
    "next"?: _lazy_0Type | undefined;
};

function _extrasOk11(_obj8: Record<string, unknown>): boolean {
    let _count9 = 0;
    for (const _k10 in _obj8) {
        _count9++;
    }
    return _count9 <= 1 + ((_obj8 as Record<PropertyKey, unknown>)["next"] !== undefined ? 1 : 0);
}

function _shapeLazy7(value: unknown, depth: number, maxDepth: number): boolean {
    if (depth >= maxDepth) {
        return false;
    }
    return isPlainObject(value) && typeof (value as Record<PropertyKey, unknown>)["value"] === "string" && ((value as Record<PropertyKey, unknown>)["next"] === undefined || _shapeLazy7((value as Record<PropertyKey, unknown>)["next"], depth + 1, maxDepth)) && _extrasOk11(value as Record<PropertyKey, unknown>);
}

function _lazy_0(value: unknown, depth: number, maxDepth: number): InternalParseResult<{
    "value": string;
    "next"?: _lazy_0Type | undefined;
}> {
    if (depth >= maxDepth) {
        return { type: "leaf", code: issueCodes.TOO_DEEP };
    }
    if (!(isPlainObject(value))) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
    }
    let _issue1: TreeNode | undefined;
    let _value2: unknown;
    const _has3 = "value" in value;
    if (_has3) {
        _value2 = (value as Record<PropertyKey, unknown>)["value"];
        if (!(typeof _value2 === "string")) {
            _issue1 = addIssue(_issue1, { type: "nest", key: "value", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
        }
        else {
        }
    }
    let _value4: unknown;
    _value4 = (value as Record<PropertyKey, unknown>)["next"];
    if (_value4 !== undefined) {
        const _refResult5 = _lazy_0(_value4, depth + 1, maxDepth);
        if (_refResult5 !== undefined) {
            _issue1 = addIssue(_issue1, { type: "nest", key: "next", child: _refResult5 as TreeNode });
        }
    }
    else {
    }
    if (!(_has3)) {
        _issue1 = addIssue(_issue1, { type: "nest", key: "value", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    for (const _key6 in value) {
        if (!(_key6 === "value" || _key6 === "next")) {
            _issue1 = addIssue(_issue1, { type: "nest", key: _key6, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
        }
    }
    if (_issue1 !== undefined) {
        return _issue1;
    }
    return undefined;
}

function _slowLazyRecursive(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<_lazy_0Type> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    return _lazy_0(value, 0, maxDepth);
}

function _validateLazyRecursive(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<_lazy_0Type> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (_shapeLazy7(value, 0, maxDepth)) {
        return undefined;
    }
    return _slowLazyRecursive(value, options);
}

function safeParseLazyRecursive(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<_lazy_0Type> {
    const result = _validateLazyRecursive(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as _lazy_0Type };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseLazyRecursive(value: unknown, options?: {
    maxDepth?: number;
}): _lazy_0Type {
    const result = safeParseLazyRecursive(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, _lazy_0Type> & {
    safeParse: typeof safeParseLazyRecursive;
    parse: typeof parseLazyRecursive;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseLazyRecursive(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseLazyRecursive,
    parse: parseLazyRecursive
};

export { _schema as LazyRecursive };
