// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseLiteralNumber(value: unknown): ParseResult<5> {
    if (!(value === 5)) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_VALUE, expected: "5" });
    }
    return { ok: true as const, value: value as 5 };
}

export function parseLiteralNumber(value: unknown): 5 {
    const result = safeParseLiteralNumber(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
