// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseLiteralBigint(value: unknown): ParseResult<5n> {
    if (!(value === 5n)) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_VALUE, expected: "5n" });
    }
    return { ok: true as const, value: value as 5n };
}

export function parseLiteralBigint(value: unknown): 5n {
    const result = safeParseLiteralBigint(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
