// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateLiteralString(value: unknown): InternalParseResult<"x"> {
    if (!(value === "x")) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "'x'" };
    }
    return undefined;
}

function safeParseLiteralString(value: unknown): ParseResult<"x"> {
    const result = _validateLiteralString(value);
    if (result === undefined) {
        return { ok: true as const, value: value as "x" };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseLiteralString(value: unknown): "x" {
    const result = safeParseLiteralString(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, "x"> & {
    safeParse: typeof safeParseLiteralString;
    parse: typeof parseLiteralString;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseLiteralString(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseLiteralString,
    parse: parseLiteralString
};

export { _schema as LiteralString };
