// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateLiteralBigint(value: unknown): InternalParseResult<5n> {
    if (!(value === 5n)) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "5n" };
    }
    return undefined;
}

function safeParseLiteralBigint(value: unknown): ParseResult<5n> {
    const result = _validateLiteralBigint(value);
    if (result === undefined) {
        return { ok: true as const, value: value as 5n };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseLiteralBigint(value: unknown): 5n {
    const result = safeParseLiteralBigint(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, 5n> & {
    safeParse: typeof safeParseLiteralBigint;
    parse: typeof parseLiteralBigint;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseLiteralBigint(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseLiteralBigint,
    parse: parseLiteralBigint
};

export { _schema as LiteralBigint };
