// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateLiteralString(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<"x"> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(value === "x")) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "'x'" };
    }
    return undefined;
}

function safeParseLiteralString(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<"x"> {
    const result = _validateLiteralString(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as "x" };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseLiteralString(value: unknown, options?: {
    maxDepth?: number;
}): "x" {
    const result = safeParseLiteralString(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, "x"> & {
    safeParse: typeof safeParseLiteralString;
    parse: typeof parseLiteralString;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, "x">>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateLiteralString(value);
            if (result === undefined) {
                return { value: value as "x" };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: "x";
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseLiteralString,
    parse: parseLiteralString
};

export { _schema as LiteralString };
