// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseLiteralString(value: unknown): ParseResult<"x"> {
    if (!(value === "x")) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_VALUE, expected: "'x'" });
    }
    return { ok: true as const, value: value as "x" };
}

export function parseLiteralString(value: unknown): "x" {
    const result = safeParseLiteralString(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
