// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateLiteralNumber(value: unknown): InternalParseResult<5> {
    if (!(value === 5)) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "5" };
    }
    return undefined;
}

function safeParseLiteralNumber(value: unknown): ParseResult<5> {
    const result = _validateLiteralNumber(value);
    if (result === undefined) {
        return { ok: true as const, value: value as 5 };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseLiteralNumber(value: unknown): 5 {
    const result = safeParseLiteralNumber(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, 5> & {
    safeParse: typeof safeParseLiteralNumber;
    parse: typeof parseLiteralNumber;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseLiteralNumber(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseLiteralNumber,
    parse: parseLiteralNumber
};

export { _schema as LiteralNumber };
