// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateLiteralBigint(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<5n> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(value === 5n)) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "5n" };
    }
    return undefined;
}

function safeParseLiteralBigint(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<5n> {
    const result = _validateLiteralBigint(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as 5n };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseLiteralBigint(value: unknown, options?: {
    maxDepth?: number;
}): 5n {
    const result = safeParseLiteralBigint(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, 5n> & {
    safeParse: typeof safeParseLiteralBigint;
    parse: typeof parseLiteralBigint;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, 5n>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateLiteralBigint(value);
            if (result === undefined) {
                return { value: value as 5n };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: 5n;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseLiteralBigint,
    parse: parseLiteralBigint
};

export { _schema as LiteralBigint };
