// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

function _shapeMap7(_m5: Map<unknown, unknown>): boolean {
    for (const _entry6 of _m5) {
        const _mk1 = _entry6[0];
        const _mv2 = _entry6[1];
        if (!(typeof _mk1 === "string")) {
            return false;
        }
        if (!(typeof _mv2 === "number" && !(Number.isNaN(_mv2)))) {
            return false;
        }
    }
    return true;
}

function _slowMap(value: unknown): ParseResult<Map<string, number>> {
    {
        if (!(value instanceof Map)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Map" });
        }
        let _issue8: TreeNode | undefined;
        let _index9 = 0;
        for (const [_key10, _value11] of value) {
            let _childIssue12: TreeNode | undefined;
            if (!(typeof _key10 === "string")) {
                _childIssue12 = addIssue(_childIssue12, { type: "nest", key: 0, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
            if (!(typeof _value11 === "number" && !(Number.isNaN(_value11)))) {
                _childIssue12 = addIssue(_childIssue12, { type: "nest", key: 1, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
            if (_childIssue12 !== undefined) {
                _issue8 = addIssue(_issue8, { type: "nest", key: _index9, child: _childIssue12 });
            }
            _index9++;
        }
        if (_issue8 !== undefined) {
            return new ParseErrorResult(_issue8);
        }
        return { ok: true as const, value: value as Map<string, number> };
    }
    return { ok: true as const, value: value as Map<string, number> };
}

export function safeParseMap(value: unknown): ParseResult<Map<string, number>> {
    if (value instanceof Map && _shapeMap7(value)) {
        return { ok: true as const, value: value as Map<string, number> };
    }
    return _slowMap(value);
}

export function parseMap(value: unknown): Map<string, number> {
    const result = safeParseMap(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
