// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _shapeMap7(_m5: Map<unknown, unknown>): boolean {
    for (const _entry6 of _m5) {
        const _mk1 = _entry6[0];
        const _mv2 = _entry6[1];
        if (!(typeof _mk1 === "string")) {
            return false;
        }
        if (!(typeof _mv2 === "number" && !(Number.isNaN(_mv2)))) {
            return false;
        }
    }
    return true;
}

const _default0 = 0;

function _slowMapDefaultValue(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Map<string, number>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Map)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Map" };
        }
        let _issue8: TreeNode | undefined;
        let _newMap9: Map<unknown, unknown> | undefined;
        let _index10 = 0;
        for (const [_key11, _value12] of value) {
            let _childIssue13: TreeNode | undefined;
            let _modifiedValue14: unknown = _value12;
            let _valueModified15 = false;
            if (!(typeof _key11 === "string")) {
                _childIssue13 = addIssue(_childIssue13, { type: "nest", key: 0, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
            if (_value12 === undefined) {
                _modifiedValue14 = _default0;
                _valueModified15 = true;
            }
            else {
                if (!(typeof _value12 === "number" && !(Number.isNaN(_value12)))) {
                    _childIssue13 = addIssue(_childIssue13, { type: "nest", key: 1, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                }
                else {
                }
            }
            if (_childIssue13 !== undefined) {
                if (_newMap9 !== undefined) {
                    _newMap9.set(_key11, _value12);
                }
                _issue8 = addIssue(_issue8, { type: "nest", key: _index10, child: _childIssue13 });
            }
            else {
                if (_valueModified15) {
                    if (_newMap9 === undefined) {
                        _newMap9 = new Map();
                        let _prevIndex18 = 0;
                        for (const [_prevKey16, _prevValue17] of value) {
                            if (_prevIndex18 >= _index10) {
                                break;
                            }
                            _newMap9.set(_prevKey16, _prevValue17);
                            _prevIndex18++;
                        }
                    }
                    _newMap9.set(_key11, _modifiedValue14);
                }
                else {
                    if (_newMap9 !== undefined) {
                        _newMap9.set(_key11, _value12);
                    }
                }
            }
            _index10++;
        }
        if (_issue8 !== undefined) {
            return _issue8;
        }
        if (_newMap9 !== undefined) {
            if (_newMap9.size !== _index10) {
                return { type: "leaf", code: issueCodes.DUPLICATE_KEY };
            }
        }
        if (_newMap9 !== undefined) {
            return { ok: true as const, value: _newMap9 as Map<string, number> };
        }
        return undefined;
    }
    return undefined;
}

function _validateMapDefaultValue(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Map<string, number>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value instanceof Map && _shapeMap7(value)) {
        return undefined;
    }
    return _slowMapDefaultValue(value, options);
}

function safeParseMapDefaultValue(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Map<string, number>> {
    const result = _validateMapDefaultValue(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Map<string, number> };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseMapDefaultValue(value: unknown, options?: {
    maxDepth?: number;
}): Map<string, number> {
    const result = safeParseMapDefaultValue(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Map<string, number>> & {
    safeParse: typeof safeParseMapDefaultValue;
    parse: typeof parseMapDefaultValue;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, Map<string, number>>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateMapDefaultValue(value);
            if (result === undefined) {
                return { value: value as Map<string, number> };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: Map<string, number>;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseMapDefaultValue,
    parse: parseMapDefaultValue
};

export { _schema as MapDefaultValue };
