// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

function _shapeMap7(_m5: Map<unknown, unknown>): boolean {
    for (const _entry6 of _m5) {
        const _mk1 = _entry6[0];
        const _mv2 = _entry6[1];
        if (!(typeof _mk1 === "string")) {
            return false;
        }
        if (!(typeof _mv2 === "number" && !(Number.isNaN(_mv2)))) {
            return false;
        }
    }
    return true;
}

const _default0 = deepFreeze(structuredClone(0));

function _slowMapDefaultValue(value: unknown): ParseResult<Map<string, Exclude<number, undefined>>> {
    {
        if (!(value instanceof Map)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Map" });
        }
        let _issue8: TreeNode | undefined;
        let _newMap9: Map<unknown, unknown> | undefined;
        let _index10 = 0;
        for (const [_key11, _value12] of value) {
            let _childIssue13: TreeNode | undefined;
            let _modifiedValue14: unknown = _value12;
            let _valueModified15 = false;
            if (!(typeof _key11 === "string")) {
                _childIssue13 = addIssue(_childIssue13, { type: "nest", key: 0, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
            if (_value12 === undefined) {
                _modifiedValue14 = _default0;
                _valueModified15 = true;
            }
            else {
                if (!(typeof _value12 === "number" && !(Number.isNaN(_value12)))) {
                    _childIssue13 = addIssue(_childIssue13, { type: "nest", key: 1, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                }
                else {
                }
            }
            if (_childIssue13 !== undefined) {
                if (_newMap9 !== undefined) {
                    _newMap9.set(_key11, _value12);
                }
                _issue8 = addIssue(_issue8, { type: "nest", key: _index10, child: _childIssue13 });
            }
            else {
                if (_valueModified15) {
                    if (_newMap9 === undefined) {
                        _newMap9 = new Map();
                        let _prevIndex18 = 0;
                        for (const [_prevKey16, _prevValue17] of value) {
                            if (_prevIndex18 >= _index10) {
                                break;
                            }
                            _newMap9.set(_prevKey16, _prevValue17);
                            _prevIndex18++;
                        }
                    }
                    _newMap9.set(_key11, _modifiedValue14);
                }
                else {
                    if (_newMap9 !== undefined) {
                        _newMap9.set(_key11, _value12);
                    }
                }
            }
            _index10++;
        }
        if (_issue8 !== undefined) {
            return new ParseErrorResult(_issue8);
        }
        if (_newMap9 !== undefined) {
            if (_newMap9.size !== _index10) {
                return new ParseErrorResult({ type: "leaf", code: issueCodes.DUPLICATE_KEY });
            }
        }
        if (_newMap9 !== undefined) {
            return { ok: true as const, value: _newMap9 as Map<string, Exclude<number, undefined>> };
        }
        return { ok: true as const, value: value as Map<string, Exclude<number, undefined>> };
    }
    return { ok: true as const, value: value as Map<string, Exclude<number, undefined>> };
}

export function safeParseMapDefaultValue(value: unknown): ParseResult<Map<string, Exclude<number, undefined>>> {
    if (value instanceof Map && _shapeMap7(value)) {
        return { ok: true as const, value: value as Map<string, Exclude<number, undefined>> };
    }
    return _slowMapDefaultValue(value);
}

export function parseMapDefaultValue(value: unknown): Map<string, Exclude<number, undefined>> {
    const result = safeParseMapDefaultValue(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
