// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    // Object.freeze doesn't stop Map/Set mutation through their methods, so shadow the mutators with throwing
    // own properties before freezing. Entries live in internal slots the ownKeys walk below can't reach, so
    // freeze them here too. Mirrors paseri-lib's utils.ts deepFreeze exactly — keep them in lockstep.
    if (value instanceof Map || value instanceof Set) {
        if (value instanceof Map) {
            for (const [key, inner] of value) {
                deepFreeze(key);
                deepFreeze(inner);
            }
        }
        else {
            for (const item of value) {
                deepFreeze(item);
            }
        }
        const reject = (): never => {
            throw new TypeError("Cannot mutate a frozen default value.");
        };
        const mutators = value instanceof Map ? ["set", "delete", "clear"] : ["add", "delete", "clear"];
        for (const mutator of mutators) {
            Object.defineProperty(value, mutator, {
                value: reject,
                writable: false,
                enumerable: false,
                configurable: false,
            });
        }
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

const _default0 = deepFreeze(["a"]);

function _validateMutableDefault(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string[]> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value === undefined) {
        return { ok: true as const, value: _default0 as string[] };
    }
    {
        if (!(Array.isArray(value))) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" };
        }
        let _issue1: TreeNode | undefined;
        for (let _index2 = 0; _index2 < value.length; _index2++) {
            let _element3 = value[_index2];
            if (!(typeof _element3 === "string")) {
                _issue1 = addIssue(_issue1, { type: "nest", key: _index2, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
        }
        if (_issue1 !== undefined) {
            return _issue1;
        }
        return undefined;
    }
    return undefined;
}

function safeParseMutableDefault(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<string[]> {
    const result = _validateMutableDefault(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as string[] };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseMutableDefault(value: unknown, options?: {
    maxDepth?: number;
}): string[] {
    const result = safeParseMutableDefault(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string[]> & {
    safeParse: typeof safeParseMutableDefault;
    parse: typeof parseMutableDefault;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseMutableDefault(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseMutableDefault,
    parse: parseMutableDefault
};

export { _schema as MutableDefault };
