// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseNever(value: unknown): ParseResult<never> {
    if (!(false)) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "never" });
    }
    return { ok: true as const, value: value as never };
}

export function parseNever(value: unknown): never {
    const result = safeParseNever(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
