// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateNever(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<never> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(false)) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "never" };
    }
    return undefined;
}

function safeParseNever(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<never> {
    const result = _validateNever(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as never };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseNever(value: unknown, options?: {
    maxDepth?: number;
}): never {
    const result = safeParseNever(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, never> & {
    safeParse: typeof safeParseNever;
    parse: typeof parseNever;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, never>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateNever(value);
            if (result === undefined) {
                return { value: value as never };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: never;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseNever,
    parse: parseNever
};

export { _schema as Never };
