// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateNever(value: unknown): InternalParseResult<never> {
    if (!(false)) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "never" };
    }
    return undefined;
}

function safeParseNever(value: unknown): ParseResult<never> {
    const result = _validateNever(value);
    if (result === undefined) {
        return { ok: true as const, value: value as never };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseNever(value: unknown): never {
    const result = safeParseNever(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, never> & {
    safeParse: typeof safeParseNever;
    parse: typeof parseNever;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseNever(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseNever,
    parse: parseNever
};

export { _schema as Never };
