// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateNullable(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<number | null> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value !== null) {
        {
            if (!(typeof value === "number" && !(Number.isNaN(value)))) {
                return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" };
            }
        }
    }
    else {
        return undefined;
    }
    return undefined;
}

function safeParseNullable(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<number | null> {
    const result = _validateNullable(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as number | null };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseNullable(value: unknown, options?: {
    maxDepth?: number;
}): number | null {
    const result = safeParseNullable(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, number | null> & {
    safeParse: typeof safeParseNullable;
    parse: typeof parseNullable;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseNullable(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseNullable,
    parse: parseNullable
};

export { _schema as Nullable };
