// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseNullable(value: unknown): ParseResult<number | null> {
    if (value !== null) {
        {
            if (!(typeof value === "number" && !(Number.isNaN(value)))) {
                return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
            }
        }
    }
    else {
        return { ok: true as const, value: value as number | null };
    }
    return { ok: true as const, value: value as number | null };
}

export function parseNullable(value: unknown): number | null {
    const result = safeParseNullable(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
