// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateNull(value: unknown): InternalParseResult<null> {
    if (!(value === null)) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "null" };
    }
    return undefined;
}

function safeParseNull(value: unknown): ParseResult<null> {
    const result = _validateNull(value);
    if (result === undefined) {
        return { ok: true as const, value: value as null };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseNull(value: unknown): null {
    const result = safeParseNull(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, null> & {
    safeParse: typeof safeParseNull;
    parse: typeof parseNull;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseNull(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseNull,
    parse: parseNull
};

export { _schema as Null };
