// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateNull(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<null> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(value === null)) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "null" };
    }
    return undefined;
}

function safeParseNull(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<null> {
    const result = _validateNull(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as null };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseNull(value: unknown, options?: {
    maxDepth?: number;
}): null {
    const result = safeParseNull(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, null> & {
    safeParse: typeof safeParseNull;
    parse: typeof parseNull;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, null>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateNull(value);
            if (result === undefined) {
                return { value: value as null };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: null;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseNull,
    parse: parseNull
};

export { _schema as Null };
