// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseNull(value: unknown): ParseResult<null> {
    if (!(value === null)) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_VALUE, expected: "null" });
    }
    return { ok: true as const, value: value as null };
}

export function parseNull(value: unknown): null {
    const result = safeParseNull(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
