// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateNumberConstrained(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<number> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(typeof value === "number" && !(Number.isNaN(value)))) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" };
        }
        if (!(value >= 0)) {
            return { type: "leaf", code: issueCodes.TOO_SMALL };
        }
        if (!(value <= 100)) {
            return { type: "leaf", code: issueCodes.TOO_LARGE };
        }
    }
    return undefined;
}

function safeParseNumberConstrained(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<number> {
    const result = _validateNumberConstrained(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as number };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseNumberConstrained(value: unknown, options?: {
    maxDepth?: number;
}): number {
    const result = safeParseNumberConstrained(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, number> & {
    safeParse: typeof safeParseNumberConstrained;
    parse: typeof parseNumberConstrained;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseNumberConstrained(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseNumberConstrained,
    parse: parseNumberConstrained
};

export { _schema as NumberConstrained };
