// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseNumberConstrained(value: unknown): ParseResult<number> {
    {
        if (!(typeof value === "number" && !(Number.isNaN(value)))) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
        }
        if (!(value >= 0)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.TOO_SMALL });
        }
        if (!(value <= 100)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.TOO_LARGE });
        }
    }
    return { ok: true as const, value: value as number };
}

export function parseNumberConstrained(value: unknown): number {
    const result = safeParseNumberConstrained(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
