// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _slowObjectPassthrough(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "foo": string;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
    }
    let _issue2: TreeNode | undefined;
    let _value3: unknown;
    const _has4 = "foo" in value;
    if (_has4) {
        _value3 = (value as Record<PropertyKey, unknown>)["foo"];
        if (!(typeof _value3 === "string")) {
            _issue2 = addIssue(_issue2, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
        }
        else {
        }
    }
    if (!(_has4)) {
        _issue2 = addIssue(_issue2, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    if (_issue2 !== undefined) {
        return _issue2;
    }
    return undefined;
}

function _validateObjectPassthrough(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "foo": string;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return _slowObjectPassthrough(value, options);
    }
    const _field1 = (value as Record<PropertyKey, unknown>)["foo"];
    if (!(typeof _field1 === "string")) {
        return _slowObjectPassthrough(value, options);
    }
    return undefined;
}

function safeParseObjectPassthrough(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<{
    "foo": string;
}> {
    const result = _validateObjectPassthrough(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "foo": string;
            } };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseObjectPassthrough(value: unknown, options?: {
    maxDepth?: number;
}): {
    "foo": string;
} {
    const result = safeParseObjectPassthrough(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "foo": string;
}> & {
    safeParse: typeof safeParseObjectPassthrough;
    parse: typeof parseObjectPassthrough;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, {
        "foo": string;
    }>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateObjectPassthrough(value);
            if (result === undefined) {
                return { value: value as {
                        "foo": string;
                    } };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: {
                            "foo": string;
                        };
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseObjectPassthrough,
    parse: parseObjectPassthrough
};

export { _schema as ObjectPassthrough };
