// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _slowObjectCollectionFields(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "tags": string[];
    "perms": Set<string>;
    "flags": Map<string, boolean>;
    "meta": Record<string, string>;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
    }
    let _issue15: TreeNode | undefined;
    let _value16: unknown;
    const _has17 = "tags" in value;
    if (_has17) {
        _value16 = (value as Record<PropertyKey, unknown>)["tags"];
        if (!(Array.isArray(_value16))) {
            _issue15 = addIssue(_issue15, { type: "nest", key: "tags", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" } });
        }
        else {
            let _issue18: TreeNode | undefined;
            for (let _index19 = 0; _index19 < _value16.length; _index19++) {
                let _element20 = _value16[_index19];
                if (!(typeof _element20 === "string")) {
                    _issue18 = addIssue(_issue18, { type: "nest", key: _index19, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                }
                else {
                }
            }
            if (_issue18 !== undefined) {
                _issue15 = addIssue(_issue15, { type: "nest", key: "tags", child: _issue18 });
            }
        }
    }
    let _value21: unknown;
    const _has22 = "perms" in value;
    if (_has22) {
        _value21 = (value as Record<PropertyKey, unknown>)["perms"];
        if (!(_value21 instanceof Set)) {
            _issue15 = addIssue(_issue15, { type: "nest", key: "perms", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Set" } });
        }
        else {
            let _issue23: TreeNode | undefined;
            let _index24 = 0;
            for (const _element25 of _value21) {
                if (!(typeof _element25 === "string")) {
                    _issue23 = addIssue(_issue23, { type: "nest", key: _index24, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                }
                else {
                }
                _index24++;
            }
            if (_issue23 !== undefined) {
                _issue15 = addIssue(_issue15, { type: "nest", key: "perms", child: _issue23 });
            }
        }
    }
    let _value26: unknown;
    const _has27 = "flags" in value;
    if (_has27) {
        _value26 = (value as Record<PropertyKey, unknown>)["flags"];
        if (!(_value26 instanceof Map)) {
            _issue15 = addIssue(_issue15, { type: "nest", key: "flags", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Map" } });
        }
        else {
            let _issue28: TreeNode | undefined;
            let _index29 = 0;
            for (const [_key30, _value31] of _value26) {
                let _childIssue32: TreeNode | undefined;
                if (!(typeof _key30 === "string")) {
                    _childIssue32 = addIssue(_childIssue32, { type: "nest", key: 0, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                }
                else {
                }
                if (!(typeof _value31 === "boolean")) {
                    _childIssue32 = addIssue(_childIssue32, { type: "nest", key: 1, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "boolean" } });
                }
                if (_childIssue32 !== undefined) {
                    _issue28 = addIssue(_issue28, { type: "nest", key: _index29, child: _childIssue32 });
                }
                _index29++;
            }
            if (_issue28 !== undefined) {
                _issue15 = addIssue(_issue15, { type: "nest", key: "flags", child: _issue28 });
            }
        }
    }
    let _value33: unknown;
    const _has34 = "meta" in value;
    if (_has34) {
        _value33 = (value as Record<PropertyKey, unknown>)["meta"];
        if (!(isPlainObject(_value33))) {
            _issue15 = addIssue(_issue15, { type: "nest", key: "meta", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Record" } });
        }
        else {
            let _issue35: TreeNode | undefined;
            for (const _key36 in _value33) {
                let _value37 = (_value33 as Record<PropertyKey, unknown>)[_key36];
                if (!(typeof _value37 === "string")) {
                    _issue35 = addIssue(_issue35, { type: "nest", key: _key36, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                }
                else {
                }
            }
            if (_issue35 !== undefined) {
                _issue15 = addIssue(_issue15, { type: "nest", key: "meta", child: _issue35 });
            }
        }
    }
    if (!(_has17)) {
        _issue15 = addIssue(_issue15, { type: "nest", key: "tags", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    if (!(_has22)) {
        _issue15 = addIssue(_issue15, { type: "nest", key: "perms", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    if (!(_has27)) {
        _issue15 = addIssue(_issue15, { type: "nest", key: "flags", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    if (!(_has34)) {
        _issue15 = addIssue(_issue15, { type: "nest", key: "meta", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    let _count39 = 0;
    for (const _k40 in value) {
        _count39++;
    }
    if (_count39 !== 4 || !(_has17) || !(_has22) || !(_has27) || !(_has34)) {
        for (const _key38 in value) {
            if (!(_key38 === "tags" || _key38 === "perms" || _key38 === "flags" || _key38 === "meta")) {
                _issue15 = addIssue(_issue15, { type: "nest", key: _key38, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
            }
        }
    }
    if (_issue15 !== undefined) {
        return _issue15;
    }
    return undefined;
}

function _validateObjectCollectionFields(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "tags": string[];
    "perms": Set<string>;
    "flags": Map<string, boolean>;
    "meta": Record<string, string>;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return _slowObjectCollectionFields(value, options);
    }
    const _field1 = (value as Record<PropertyKey, unknown>)["tags"];
    if (!(Array.isArray(_field1))) {
        return _slowObjectCollectionFields(value, options);
    }
    for (let _i3 = 0; _i3 < _field1.length; _i3++) {
        const _el2 = _field1[_i3];
        if (!(typeof _el2 === "string")) {
            return _slowObjectCollectionFields(value, options);
        }
    }
    const _field4 = (value as Record<PropertyKey, unknown>)["perms"];
    if (!(_field4 instanceof Set)) {
        return _slowObjectCollectionFields(value, options);
    }
    for (const _el5 of _field4) {
        if (!(typeof _el5 === "string")) {
            return _slowObjectCollectionFields(value, options);
        }
    }
    const _field6 = (value as Record<PropertyKey, unknown>)["flags"];
    if (!(_field6 instanceof Map)) {
        return _slowObjectCollectionFields(value, options);
    }
    for (const _entry9 of _field6) {
        const _mk7 = _entry9[0];
        const _mv8 = _entry9[1];
        if (!(typeof _mk7 === "string")) {
            return _slowObjectCollectionFields(value, options);
        }
        if (!(typeof _mv8 === "boolean")) {
            return _slowObjectCollectionFields(value, options);
        }
    }
    const _field10 = (value as Record<PropertyKey, unknown>)["meta"];
    if (!(isPlainObject(_field10))) {
        return _slowObjectCollectionFields(value, options);
    }
    for (const _k12 in _field10) {
        const _el11 = _field10[_k12];
        if (!(typeof _el11 === "string")) {
            return _slowObjectCollectionFields(value, options);
        }
    }
    let _count13 = 0;
    for (const _k14 in value) {
        _count13++;
    }
    if (_count13 > 4) {
        return _slowObjectCollectionFields(value, options);
    }
    return undefined;
}

function safeParseObjectCollectionFields(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<{
    "tags": string[];
    "perms": Set<string>;
    "flags": Map<string, boolean>;
    "meta": Record<string, string>;
}> {
    const result = _validateObjectCollectionFields(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "tags": string[];
                "perms": Set<string>;
                "flags": Map<string, boolean>;
                "meta": Record<string, string>;
            } };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseObjectCollectionFields(value: unknown, options?: {
    maxDepth?: number;
}): {
    "tags": string[];
    "perms": Set<string>;
    "flags": Map<string, boolean>;
    "meta": Record<string, string>;
} {
    const result = safeParseObjectCollectionFields(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "tags": string[];
    "perms": Set<string>;
    "flags": Map<string, boolean>;
    "meta": Record<string, string>;
}> & {
    safeParse: typeof safeParseObjectCollectionFields;
    parse: typeof parseObjectCollectionFields;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, {
        "tags": string[];
        "perms": Set<string>;
        "flags": Map<string, boolean>;
        "meta": Record<string, string>;
    }>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateObjectCollectionFields(value);
            if (result === undefined) {
                return { value: value as {
                        "tags": string[];
                        "perms": Set<string>;
                        "flags": Map<string, boolean>;
                        "meta": Record<string, string>;
                    } };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: {
                            "tags": string[];
                            "perms": Set<string>;
                            "flags": Map<string, boolean>;
                            "meta": Record<string, string>;
                        };
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseObjectCollectionFields,
    parse: parseObjectCollectionFields
};

export { _schema as ObjectCollectionFields };
