// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (value.constructor !== Object && !Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _objectIssues17(_val9: unknown): TreeNode | undefined {
    let _issue10: TreeNode | undefined;
    if (!(isPlainObject(_val9))) {
        _issue10 = addIssue(_issue10, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" });
    }
    else {
        let _issue11: TreeNode | undefined;
        let _value12: unknown;
        const _has13 = "baz" in _val9;
        if (_has13) {
            _value12 = (_val9 as Record<PropertyKey, unknown>)["baz"];
            if (!(typeof _value12 === "number" && !(Number.isNaN(_value12)))) {
                _issue11 = addIssue(_issue11, { type: "nest", key: "baz", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
        }
        if (!(_has13)) {
            _issue11 = addIssue(_issue11, { type: "nest", key: "baz", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
        let _count15 = 0;
        for (const _k16 in _val9) {
            _count15++;
        }
        if (_count15 !== 1 || !(_has13)) {
            for (const _key14 in _val9) {
                if (!(_key14 === "baz")) {
                    _issue11 = addIssue(_issue11, { type: "nest", key: _key14, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
                }
            }
        }
        if (_issue11 !== undefined) {
            _issue10 = addIssue(_issue10, _issue11);
        }
    }
    return _issue10;
}

function _slowObjectNested(value: unknown): ParseResult<{
    "inner": {
        "baz": number;
    };
}> {
    if (!(isPlainObject(value))) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" });
    }
    let _issue6: TreeNode | undefined;
    let _value7: unknown;
    const _has8 = "inner" in value;
    if (_has8) {
        _value7 = (value as Record<PropertyKey, unknown>)["inner"];
        const _childIssue18 = _objectIssues17(_value7);
        if (_childIssue18 !== undefined) {
            _issue6 = addIssue(_issue6, { type: "nest", key: "inner", child: _childIssue18 });
        }
    }
    if (!(_has8)) {
        _issue6 = addIssue(_issue6, { type: "nest", key: "inner", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    let _count20 = 0;
    for (const _k21 in value) {
        _count20++;
    }
    if (_count20 !== 1 || !(_has8)) {
        for (const _key19 in value) {
            if (!(_key19 === "inner")) {
                _issue6 = addIssue(_issue6, { type: "nest", key: _key19, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
            }
        }
    }
    if (_issue6 !== undefined) {
        return new ParseErrorResult(_issue6);
    }
    return { ok: true as const, value: value as {
            "inner": {
                "baz": number;
            };
        } };
}

export function safeParseObjectNested(value: unknown): ParseResult<{
    "inner": {
        "baz": number;
    };
}> {
    if (!(isPlainObject(value))) {
        return _slowObjectNested(value);
    }
    const _field1 = (value as Record<PropertyKey, unknown>)["inner"];
    if (!(isPlainObject(_field1) && (typeof (_field1 as Record<PropertyKey, unknown>)["baz"] === "number" && !(Number.isNaN((_field1 as Record<PropertyKey, unknown>)["baz"]))))) {
        return _slowObjectNested(value);
    }
    let _count2 = 0;
    for (const _k3 in _field1) {
        _count2++;
    }
    if (_count2 > 1) {
        return _slowObjectNested(value);
    }
    let _count4 = 0;
    for (const _k5 in value) {
        _count4++;
    }
    if (_count4 > 1) {
        return _slowObjectNested(value);
    }
    return { ok: true as const, value: value as {
            "inner": {
                "baz": number;
            };
        } };
}

export function parseObjectNested(value: unknown): {
    "inner": {
        "baz": number;
    };
} {
    const result = safeParseObjectNested(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
