// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (value.constructor !== Object && !Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

const _default0 = deepFreeze(structuredClone(0));

function _slowObjectDefault(value: unknown): ParseResult<{
    "foo": string;
    "count": Exclude<number, undefined>;
}> {
    if (!(isPlainObject(value))) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" });
    }
    let _issue4: TreeNode | undefined;
    let _modified5: Record<string, unknown> | undefined;
    let _hasModification6 = false;
    let _unrecognized7: Set<string> | undefined;
    let _seen_foo8 = false;
    let _seen_count9 = false;
    for (const _key10 in value) {
        switch (_key10) {
            case "foo":
                _seen_foo8 = true;
                let _value11 = (value as Record<PropertyKey, unknown>)["foo"];
                if (!(typeof _value11 === "string")) {
                    _issue4 = addIssue(_issue4, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                }
                else {
                }
                break;
            case "count":
                _seen_count9 = true;
                let _value12 = (value as Record<PropertyKey, unknown>)["count"];
                let _fieldModified13 = false;
                if (_value12 === undefined) {
                    _value12 = _default0;
                    _fieldModified13 = true;
                }
                else {
                    if (!(typeof _value12 === "number" && !(Number.isNaN(_value12)))) {
                        _issue4 = addIssue(_issue4, { type: "nest", key: "count", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                    }
                    else {
                    }
                }
                if (_fieldModified13) {
                    if (_modified5 === undefined) {
                        _modified5 = { ...value as Record<PropertyKey, unknown> };
                    }
                    _modified5["count"] = _value12;
                    _hasModification6 = true;
                }
                break;
            default:
                if (_unrecognized7 === undefined) {
                    _unrecognized7 = new Set();
                }
                _unrecognized7.add(_key10);
        }
    }
    if (!(_seen_foo8)) {
        if ("foo" in (value as Record<PropertyKey, unknown>)) {
            let _value11 = (value as Record<PropertyKey, unknown>)["foo"];
            if (!(typeof _value11 === "string")) {
                _issue4 = addIssue(_issue4, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
        }
        else {
            _issue4 = addIssue(_issue4, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
    }
    if (!(_seen_count9)) {
        if ("count" in (value as Record<PropertyKey, unknown>)) {
            let _value12 = (value as Record<PropertyKey, unknown>)["count"];
            let _fieldModified13 = false;
            if (_value12 === undefined) {
                _value12 = _default0;
                _fieldModified13 = true;
            }
            else {
                if (!(typeof _value12 === "number" && !(Number.isNaN(_value12)))) {
                    _issue4 = addIssue(_issue4, { type: "nest", key: "count", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                }
                else {
                }
            }
            if (_fieldModified13) {
                if (_modified5 === undefined) {
                    _modified5 = { ...value as Record<PropertyKey, unknown> };
                }
                _modified5["count"] = _value12;
                _hasModification6 = true;
            }
        }
        else {
            if (_modified5 === undefined) {
                _modified5 = { ...value as Record<PropertyKey, unknown> };
            }
            _modified5["count"] = _default0;
            _hasModification6 = true;
        }
    }
    if (_unrecognized7 !== undefined) {
        for (const _unrecognizedKey14 of _unrecognized7) {
            _issue4 = addIssue(_issue4, { type: "nest", key: _unrecognizedKey14, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
        }
    }
    if (_issue4 !== undefined) {
        return new ParseErrorResult(_issue4);
    }
    if (_hasModification6) {
        return { ok: true as const, value: _modified5 as {
                "foo": string;
                "count": Exclude<number, undefined>;
            } };
    }
    else {
        return { ok: true as const, value: value as {
                "foo": string;
                "count": Exclude<number, undefined>;
            } };
    }
    return { ok: true as const, value: value as {
            "foo": string;
            "count": Exclude<number, undefined>;
        } };
}

export function safeParseObjectDefault(value: unknown): ParseResult<{
    "foo": string;
    "count": Exclude<number, undefined>;
}> {
    if (typeof value === "object" && value !== null && typeof (value as Record<PropertyKey, unknown>)["foo"] === "string" && ((value as Record<PropertyKey, unknown>)["count"] === undefined || typeof (value as Record<PropertyKey, unknown>)["count"] === "number" && !(Number.isNaN((value as Record<PropertyKey, unknown>)["count"]))) && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null)) {
        let _count2 = 0;
        for (const _k3 in value) {
            _count2++;
        }
        if (_count2 > 1 + ((value as Record<PropertyKey, unknown>)["count"] !== undefined ? 1 : 0)) {
            return _slowObjectDefault(value);
        }
        {
            if ((value as Record<PropertyKey, unknown>)["count"] === undefined) {
                const _out1 = { ...value as Record<PropertyKey, unknown> };
                if ((value as Record<PropertyKey, unknown>)["count"] === undefined) {
                    _out1["count"] = _default0;
                }
                return { ok: true as const, value: _out1 as {
                        "foo": string;
                        "count": Exclude<number, undefined>;
                    } };
            }
            return { ok: true as const, value: value as {
                    "foo": string;
                    "count": Exclude<number, undefined>;
                } };
        }
    }
    return _slowObjectDefault(value);
}

export function parseObjectDefault(value: unknown): {
    "foo": string;
    "count": Exclude<number, undefined>;
} {
    const result = safeParseObjectDefault(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
