// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

const _default0 = 123;

function _slowObjectStripDefault(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "host": string;
    "port": number;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
    }
    let _issue1: TreeNode | undefined;
    let _modified2: Record<string, unknown> | undefined;
    let _hasModification3 = false;
    let _unrecognized4: Set<string> | undefined;
    let _seen_host5 = false;
    let _seen_port6 = false;
    for (const _key7 in value) {
        switch (_key7) {
            case "host":
                _seen_host5 = true;
                let _value8 = (value as Record<PropertyKey, unknown>)["host"];
                if (!(typeof _value8 === "string")) {
                    _issue1 = addIssue(_issue1, { type: "nest", key: "host", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                }
                else {
                }
                break;
            case "port":
                _seen_port6 = true;
                let _value9 = (value as Record<PropertyKey, unknown>)["port"];
                let _fieldModified10 = false;
                if (_value9 === undefined) {
                    _value9 = _default0;
                    _fieldModified10 = true;
                }
                else {
                    if (!(typeof _value9 === "number" && !(Number.isNaN(_value9)))) {
                        _issue1 = addIssue(_issue1, { type: "nest", key: "port", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                    }
                    else {
                    }
                }
                if (_fieldModified10) {
                    if (_modified2 === undefined) {
                        _modified2 = {};
                    }
                    _modified2["port"] = _value9;
                    _hasModification3 = true;
                }
                break;
            default:
                if (_unrecognized4 === undefined) {
                    _unrecognized4 = new Set();
                }
                _unrecognized4.add(_key7);
        }
    }
    if (!(_seen_host5)) {
        if ("host" in (value as Record<PropertyKey, unknown>)) {
            let _value8 = (value as Record<PropertyKey, unknown>)["host"];
            if (!(typeof _value8 === "string")) {
                _issue1 = addIssue(_issue1, { type: "nest", key: "host", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
        }
        else {
            _issue1 = addIssue(_issue1, { type: "nest", key: "host", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
    }
    if (!(_seen_port6)) {
        if ("port" in (value as Record<PropertyKey, unknown>)) {
            let _value9 = (value as Record<PropertyKey, unknown>)["port"];
            let _fieldModified10 = false;
            if (_value9 === undefined) {
                _value9 = _default0;
                _fieldModified10 = true;
            }
            else {
                if (!(typeof _value9 === "number" && !(Number.isNaN(_value9)))) {
                    _issue1 = addIssue(_issue1, { type: "nest", key: "port", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                }
                else {
                }
            }
            if (_fieldModified10) {
                if (_modified2 === undefined) {
                    _modified2 = {};
                }
                _modified2["port"] = _value9;
                _hasModification3 = true;
            }
        }
        else {
            if (_modified2 === undefined) {
                _modified2 = {};
            }
            _modified2["port"] = _default0;
            _hasModification3 = true;
        }
    }
    if (_issue1 !== undefined) {
        return _issue1;
    }
    if (_unrecognized4 !== undefined) {
        const _sanitized11: Record<PropertyKey, unknown> = {};
        for (const _sanitizedKey12 in value) {
            if (_unrecognized4.has(_sanitizedKey12)) {
                continue;
            }
            if (_sanitizedKey12 === "__proto__") {
                Object.defineProperty(_sanitized11, _sanitizedKey12, { value: _hasModification3 && Object.hasOwn(_modified2 as Record<PropertyKey, unknown>, _sanitizedKey12) ? (_modified2 as Record<PropertyKey, unknown>)[_sanitizedKey12] : (value as Record<PropertyKey, unknown>)[_sanitizedKey12], writable: true, enumerable: true, configurable: true });
            }
            else {
                _sanitized11[_sanitizedKey12] = _hasModification3 && Object.hasOwn(_modified2 as Record<PropertyKey, unknown>, _sanitizedKey12) ? (_modified2 as Record<PropertyKey, unknown>)[_sanitizedKey12] : (value as Record<PropertyKey, unknown>)[_sanitizedKey12];
            }
        }
        if (_hasModification3 && _modified2 !== undefined) {
            for (const _modifiedKey13 in _modified2) {
                if (!(Object.hasOwn(value as Record<PropertyKey, unknown>, _modifiedKey13))) {
                    if (_modifiedKey13 === "__proto__") {
                        Object.defineProperty(_sanitized11, _modifiedKey13, { value: (_modified2 as Record<PropertyKey, unknown>)[_modifiedKey13], writable: true, enumerable: true, configurable: true });
                    }
                    else {
                        _sanitized11[_modifiedKey13] = (_modified2 as Record<PropertyKey, unknown>)[_modifiedKey13];
                    }
                }
            }
        }
        return { ok: true as const, value: _sanitized11 as {
                "host": string;
                "port": number;
            } };
    }
    if (_hasModification3) {
        return { ok: true as const, value: { ...value as Record<PropertyKey, unknown>, ..._modified2 } as {
                "host": string;
                "port": number;
            } };
    }
    else {
        return undefined;
    }
    return undefined;
}

function _validateObjectStripDefault(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "host": string;
    "port": number;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (isPlainObject(value) && typeof (value as Record<PropertyKey, unknown>)["host"] === "string" && ((value as Record<PropertyKey, unknown>)["port"] === undefined || typeof (value as Record<PropertyKey, unknown>)["port"] === "number" && !(Number.isNaN((value as Record<PropertyKey, unknown>)["port"])))) {
        return { ok: true as const, value: { host: (value as Record<PropertyKey, unknown>)["host"], port: (value as Record<PropertyKey, unknown>)["port"] === undefined ? _default0 : (value as Record<PropertyKey, unknown>)["port"] } as {
                "host": string;
                "port": number;
            } };
    }
    return _slowObjectStripDefault(value, options);
}

function safeParseObjectStripDefault(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<{
    "host": string;
    "port": number;
}> {
    const result = _validateObjectStripDefault(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "host": string;
                "port": number;
            } };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseObjectStripDefault(value: unknown, options?: {
    maxDepth?: number;
}): {
    "host": string;
    "port": number;
} {
    const result = safeParseObjectStripDefault(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "host": string;
    "port": number;
}> & {
    safeParse: typeof safeParseObjectStripDefault;
    parse: typeof parseObjectStripDefault;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseObjectStripDefault(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseObjectStripDefault,
    parse: parseObjectStripDefault
};

export { _schema as ObjectStripDefault };
