// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (value.constructor !== Object && !Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _slowObjectStripNested(value: unknown): InternalParseResult<{
    "inner": {
        "baz": number;
    };
}> {
    if (!(isPlainObject(value))) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
    }
    let _issue2: TreeNode | undefined;
    let _modified3: Record<string, unknown> | undefined;
    let _hasModification4 = false;
    let _unrecognized5: Set<string> | undefined;
    let _seen_inner6 = false;
    for (const _key7 in value) {
        switch (_key7) {
            case "inner":
                _seen_inner6 = true;
                let _value8 = (value as Record<PropertyKey, unknown>)["inner"];
                let _fieldModified9 = false;
                if (!(isPlainObject(_value8))) {
                    _issue2 = addIssue(_issue2, { type: "nest", key: "inner", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" } });
                }
                else {
                    let _issue10: TreeNode | undefined;
                    let _hasExtras11 = false;
                    let _value12: unknown;
                    const _has13 = "baz" in _value8;
                    if (_has13) {
                        _value12 = (_value8 as Record<PropertyKey, unknown>)["baz"];
                        if (!(typeof _value12 === "number" && !(Number.isNaN(_value12)))) {
                            _issue10 = addIssue(_issue10, { type: "nest", key: "baz", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                        }
                        else {
                        }
                    }
                    if (!(_has13)) {
                        _issue10 = addIssue(_issue10, { type: "nest", key: "baz", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
                    }
                    let _count15 = 0;
                    for (const _k16 in _value8) {
                        _count15++;
                    }
                    if (_count15 !== 1 || !(_has13)) {
                        for (const _key14 in _value8) {
                            if (!(_key14 === "baz")) {
                                _hasExtras11 = true;
                            }
                        }
                    }
                    if (_issue10 !== undefined) {
                        _issue2 = addIssue(_issue2, { type: "nest", key: "inner", child: _issue10 });
                    }
                    if (_hasExtras11) {
                        const _sanitized17: Record<PropertyKey, unknown> = {};
                        if (_has13) {
                            _sanitized17["baz"] = _value12;
                        }
                        _value8 = _sanitized17;
                        _fieldModified9 = true;
                    }
                }
                if (_fieldModified9) {
                    if (_modified3 === undefined) {
                        _modified3 = {};
                    }
                    _modified3["inner"] = _value8;
                    _hasModification4 = true;
                }
                break;
            default:
                if (_unrecognized5 === undefined) {
                    _unrecognized5 = new Set();
                }
                _unrecognized5.add(_key7);
        }
    }
    if (!(_seen_inner6)) {
        if ("inner" in (value as Record<PropertyKey, unknown>)) {
            let _value8 = (value as Record<PropertyKey, unknown>)["inner"];
            let _fieldModified9 = false;
            if (!(isPlainObject(_value8))) {
                _issue2 = addIssue(_issue2, { type: "nest", key: "inner", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" } });
            }
            else {
                let _issue10: TreeNode | undefined;
                let _hasExtras11 = false;
                let _value12: unknown;
                const _has13 = "baz" in _value8;
                if (_has13) {
                    _value12 = (_value8 as Record<PropertyKey, unknown>)["baz"];
                    if (!(typeof _value12 === "number" && !(Number.isNaN(_value12)))) {
                        _issue10 = addIssue(_issue10, { type: "nest", key: "baz", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
                    }
                    else {
                    }
                }
                if (!(_has13)) {
                    _issue10 = addIssue(_issue10, { type: "nest", key: "baz", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
                }
                let _count15 = 0;
                for (const _k16 in _value8) {
                    _count15++;
                }
                if (_count15 !== 1 || !(_has13)) {
                    for (const _key14 in _value8) {
                        if (!(_key14 === "baz")) {
                            _hasExtras11 = true;
                        }
                    }
                }
                if (_issue10 !== undefined) {
                    _issue2 = addIssue(_issue2, { type: "nest", key: "inner", child: _issue10 });
                }
                if (_hasExtras11) {
                    const _sanitized17: Record<PropertyKey, unknown> = {};
                    if (_has13) {
                        _sanitized17["baz"] = _value12;
                    }
                    _value8 = _sanitized17;
                    _fieldModified9 = true;
                }
            }
            if (_fieldModified9) {
                if (_modified3 === undefined) {
                    _modified3 = {};
                }
                _modified3["inner"] = _value8;
                _hasModification4 = true;
            }
        }
        else {
            _issue2 = addIssue(_issue2, { type: "nest", key: "inner", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
    }
    if (_issue2 !== undefined) {
        return _issue2;
    }
    if (_unrecognized5 !== undefined) {
        const _sanitized18: Record<PropertyKey, unknown> = {};
        for (const _sanitizedKey19 in value) {
            if (_unrecognized5.has(_sanitizedKey19)) {
                continue;
            }
            if (_sanitizedKey19 === "__proto__") {
                Object.defineProperty(_sanitized18, _sanitizedKey19, { value: _hasModification4 && Object.hasOwn(_modified3 as Record<PropertyKey, unknown>, _sanitizedKey19) ? (_modified3 as Record<PropertyKey, unknown>)[_sanitizedKey19] : (value as Record<PropertyKey, unknown>)[_sanitizedKey19], writable: true, enumerable: true, configurable: true });
            }
            else {
                _sanitized18[_sanitizedKey19] = _hasModification4 && Object.hasOwn(_modified3 as Record<PropertyKey, unknown>, _sanitizedKey19) ? (_modified3 as Record<PropertyKey, unknown>)[_sanitizedKey19] : (value as Record<PropertyKey, unknown>)[_sanitizedKey19];
            }
        }
        if (_hasModification4 && _modified3 !== undefined) {
            for (const _modifiedKey20 in _modified3) {
                if (!(Object.hasOwn(value as Record<PropertyKey, unknown>, _modifiedKey20))) {
                    if (_modifiedKey20 === "__proto__") {
                        Object.defineProperty(_sanitized18, _modifiedKey20, { value: (_modified3 as Record<PropertyKey, unknown>)[_modifiedKey20], writable: true, enumerable: true, configurable: true });
                    }
                    else {
                        _sanitized18[_modifiedKey20] = (_modified3 as Record<PropertyKey, unknown>)[_modifiedKey20];
                    }
                }
            }
        }
        return { ok: true as const, value: _sanitized18 as {
                "inner": {
                    "baz": number;
                };
            } };
    }
    if (_hasModification4) {
        return { ok: true as const, value: { ...value as Record<PropertyKey, unknown>, ..._modified3 } as {
                "inner": {
                    "baz": number;
                };
            } };
    }
    else {
        return undefined;
    }
    return undefined;
}

function _validateObjectStripNested(value: unknown): InternalParseResult<{
    "inner": {
        "baz": number;
    };
}> {
    if (!(isPlainObject(value))) {
        return _slowObjectStripNested(value);
    }
    const _field1 = (value as Record<PropertyKey, unknown>)["inner"];
    if (!(isPlainObject(_field1) && (typeof (_field1 as Record<PropertyKey, unknown>)["baz"] === "number" && !(Number.isNaN((_field1 as Record<PropertyKey, unknown>)["baz"]))))) {
        return _slowObjectStripNested(value);
    }
    return { ok: true as const, value: { inner: { baz: (_field1 as Record<PropertyKey, unknown>)["baz"] } } as {
            "inner": {
                "baz": number;
            };
        } };
}

function safeParseObjectStripNested(value: unknown): ParseResult<{
    "inner": {
        "baz": number;
    };
}> {
    const result = _validateObjectStripNested(value);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "inner": {
                    "baz": number;
                };
            } };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseObjectStripNested(value: unknown): {
    "inner": {
        "baz": number;
    };
} {
    const result = safeParseObjectStripNested(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "inner": {
        "baz": number;
    };
}> & {
    safeParse: typeof safeParseObjectStripNested;
    parse: typeof parseObjectStripNested;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseObjectStripNested(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseObjectStripNested,
    parse: parseObjectStripNested
};

export { _schema as ObjectStripNested };
