// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _slowObjectOptional(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "foo"?: string | undefined;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
    }
    let _issue4: TreeNode | undefined;
    let _value5: unknown;
    _value5 = (value as Record<PropertyKey, unknown>)["foo"];
    if (_value5 !== undefined) {
        if (!(typeof _value5 === "string")) {
            _issue4 = addIssue(_issue4, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
        }
        else {
        }
    }
    else {
    }
    for (const _key6 in value) {
        if (!(_key6 === "foo")) {
            _issue4 = addIssue(_issue4, { type: "nest", key: _key6, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
        }
    }
    if (_issue4 !== undefined) {
        return _issue4;
    }
    return undefined;
}

function _validateObjectOptional(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "foo"?: string | undefined;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return _slowObjectOptional(value, options);
    }
    const _field1 = (value as Record<PropertyKey, unknown>)["foo"];
    if (!(_field1 === undefined || typeof _field1 === "string")) {
        return _slowObjectOptional(value, options);
    }
    let _count2 = 0;
    for (const _k3 in value) {
        _count2++;
    }
    if (_count2 > 0 + ((value as Record<PropertyKey, unknown>)["foo"] !== undefined ? 1 : 0)) {
        return _slowObjectOptional(value, options);
    }
    return undefined;
}

function safeParseObjectOptional(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<{
    "foo"?: string | undefined;
}> {
    const result = _validateObjectOptional(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "foo"?: string | undefined;
            } };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseObjectOptional(value: unknown, options?: {
    maxDepth?: number;
}): {
    "foo"?: string | undefined;
} {
    const result = safeParseObjectOptional(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "foo"?: string | undefined;
}> & {
    safeParse: typeof safeParseObjectOptional;
    parse: typeof parseObjectOptional;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, {
        "foo"?: string | undefined;
    }>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateObjectOptional(value);
            if (result === undefined) {
                return { value: value as {
                        "foo"?: string | undefined;
                    } };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: {
                            "foo"?: string | undefined;
                        };
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseObjectOptional,
    parse: parseObjectOptional
};

export { _schema as ObjectOptional };
