// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _slowObjectStrict(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "foo": string;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
    }
    let _issue4: TreeNode | undefined;
    let _value5: unknown;
    const _has6 = "foo" in value;
    if (_has6) {
        _value5 = (value as Record<PropertyKey, unknown>)["foo"];
        if (!(typeof _value5 === "string")) {
            _issue4 = addIssue(_issue4, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
        }
        else {
        }
    }
    if (!(_has6)) {
        _issue4 = addIssue(_issue4, { type: "nest", key: "foo", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
    }
    let _count8 = 0;
    for (const _k9 in value) {
        _count8++;
    }
    if (_count8 !== 1 || !(_has6)) {
        for (const _key7 in value) {
            if (!(_key7 === "foo")) {
                _issue4 = addIssue(_issue4, { type: "nest", key: _key7, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
            }
        }
    }
    if (_issue4 !== undefined) {
        return _issue4;
    }
    return undefined;
}

function _validateObjectStrict(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "foo": string;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(isPlainObject(value))) {
        return _slowObjectStrict(value, options);
    }
    const _field1 = (value as Record<PropertyKey, unknown>)["foo"];
    if (!(typeof _field1 === "string")) {
        return _slowObjectStrict(value, options);
    }
    let _count2 = 0;
    for (const _k3 in value) {
        _count2++;
    }
    if (_count2 > 1) {
        return _slowObjectStrict(value, options);
    }
    return undefined;
}

function safeParseObjectStrict(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<{
    "foo": string;
}> {
    const result = _validateObjectStrict(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "foo": string;
            } };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseObjectStrict(value: unknown, options?: {
    maxDepth?: number;
}): {
    "foo": string;
} {
    const result = safeParseObjectStrict(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "foo": string;
}> & {
    safeParse: typeof safeParseObjectStrict;
    parse: typeof parseObjectStrict;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseObjectStrict(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseObjectStrict,
    parse: parseObjectStrict
};

export { _schema as ObjectStrict };
