// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseOptional(value: unknown): ParseResult<string | undefined> {
    if (value !== undefined) {
        {
            if (!(typeof value === "string")) {
                return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
            }
        }
    }
    else {
        return { ok: true as const, value: value as string | undefined };
    }
    return { ok: true as const, value: value as string | undefined };
}

export function parseOptional(value: unknown): string | undefined {
    const result = safeParseOptional(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
