// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateOptional(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string | undefined> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value !== undefined) {
        {
            if (!(typeof value === "string")) {
                return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" };
            }
        }
    }
    else {
        return undefined;
    }
    return undefined;
}

function safeParseOptional(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<string | undefined> {
    const result = _validateOptional(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as string | undefined };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseOptional(value: unknown, options?: {
    maxDepth?: number;
}): string | undefined {
    const result = safeParseOptional(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string | undefined> & {
    safeParse: typeof safeParseOptional;
    parse: typeof parseOptional;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseOptional(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseOptional,
    parse: parseOptional
};

export { _schema as Optional };
