// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validatePlainDateTime(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.PlainDateTime> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Temporal.PlainDateTime)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainDateTime" };
        }
    }
    return undefined;
}

function safeParsePlainDateTime(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.PlainDateTime> {
    const result = _validatePlainDateTime(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainDateTime };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parsePlainDateTime(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.PlainDateTime {
    const result = safeParsePlainDateTime(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainDateTime> & {
    safeParse: typeof safeParsePlainDateTime;
    parse: typeof parsePlainDateTime;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParsePlainDateTime(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParsePlainDateTime,
    parse: parsePlainDateTime
};

export { _schema as PlainDateTime };
