// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParsePlainMonthDay(value: unknown): ParseResult<Temporal.PlainMonthDay> {
    if (!(value instanceof Temporal.PlainMonthDay)) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainMonthDay" });
    }
    return { ok: true as const, value: value as Temporal.PlainMonthDay };
}

export function parsePlainMonthDay(value: unknown): Temporal.PlainMonthDay {
    const result = safeParsePlainMonthDay(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
