// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validatePlainMonthDay(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.PlainMonthDay> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (!(value instanceof Temporal.PlainMonthDay)) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainMonthDay" };
    }
    return undefined;
}

function safeParsePlainMonthDay(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.PlainMonthDay> {
    const result = _validatePlainMonthDay(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainMonthDay };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parsePlainMonthDay(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.PlainMonthDay {
    const result = safeParsePlainMonthDay(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainMonthDay> & {
    safeParse: typeof safeParsePlainMonthDay;
    parse: typeof parsePlainMonthDay;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, Temporal.PlainMonthDay>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validatePlainMonthDay(value);
            if (result === undefined) {
                return { value: value as Temporal.PlainMonthDay };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: Temporal.PlainMonthDay;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParsePlainMonthDay,
    parse: parsePlainMonthDay
};

export { _schema as PlainMonthDay };
