// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validatePlainYearMonth(value: unknown): InternalParseResult<Temporal.PlainYearMonth> {
    {
        if (!(value instanceof Temporal.PlainYearMonth)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainYearMonth" };
        }
    }
    return undefined;
}

function safeParsePlainYearMonth(value: unknown): ParseResult<Temporal.PlainYearMonth> {
    const result = _validatePlainYearMonth(value);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainYearMonth };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parsePlainYearMonth(value: unknown): Temporal.PlainYearMonth {
    const result = safeParsePlainYearMonth(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainYearMonth> & {
    safeParse: typeof safeParsePlainYearMonth;
    parse: typeof parsePlainYearMonth;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParsePlainYearMonth(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParsePlainYearMonth,
    parse: parsePlainYearMonth
};

export { _schema as PlainYearMonth };
