// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validatePlainTime(value: unknown): InternalParseResult<Temporal.PlainTime> {
    {
        if (!(value instanceof Temporal.PlainTime)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainTime" };
        }
    }
    return undefined;
}

function safeParsePlainTime(value: unknown): ParseResult<Temporal.PlainTime> {
    const result = _validatePlainTime(value);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainTime };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parsePlainTime(value: unknown): Temporal.PlainTime {
    const result = safeParsePlainTime(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainTime> & {
    safeParse: typeof safeParsePlainTime;
    parse: typeof parsePlainTime;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParsePlainTime(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParsePlainTime,
    parse: parsePlainTime
};

export { _schema as PlainTime };
