// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validatePlainYearMonth(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.PlainYearMonth> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Temporal.PlainYearMonth)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainYearMonth" };
        }
    }
    return undefined;
}

function safeParsePlainYearMonth(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.PlainYearMonth> {
    const result = _validatePlainYearMonth(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainYearMonth };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parsePlainYearMonth(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.PlainYearMonth {
    const result = safeParsePlainYearMonth(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainYearMonth> & {
    safeParse: typeof safeParsePlainYearMonth;
    parse: typeof parsePlainYearMonth;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParsePlainYearMonth(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParsePlainYearMonth,
    parse: parsePlainYearMonth
};

export { _schema as PlainYearMonth };
