// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParsePlainDateTime(value: unknown): ParseResult<Temporal.PlainDateTime> {
    {
        if (!(value instanceof Temporal.PlainDateTime)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainDateTime" });
        }
    }
    return { ok: true as const, value: value as Temporal.PlainDateTime };
}

export function parsePlainDateTime(value: unknown): Temporal.PlainDateTime {
    const result = safeParsePlainDateTime(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
