// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

const _bound2 = Temporal.PlainDate.from("2020-01-01");

export function safeParsePlainDate(value: unknown): ParseResult<Temporal.PlainDate> {
    {
        if (!(value instanceof Temporal.PlainDate)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainDate" });
        }
        const _iso1 = value.calendarId === "iso8601";
        if (!(_iso1 ? value.year > 2020 || value.year === 2020 && (value.month > 1 || value.month === 1 && value.day >= 1) : Temporal.PlainDate.compare(value, _bound2) >= 0)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.TOO_DATED });
        }
        if (!(_iso1 ? value.year < 2020 || value.year === 2020 && (value.month < 1 || value.month === 1 && value.day <= 1) : Temporal.PlainDate.compare(value, _bound2) <= 0)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.TOO_RECENT });
        }
    }
    return { ok: true as const, value: value as Temporal.PlainDate };
}

export function parsePlainDate(value: unknown): Temporal.PlainDate {
    const result = safeParsePlainDate(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
