// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validatePlainTime(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.PlainTime> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Temporal.PlainTime)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainTime" };
        }
    }
    return undefined;
}

function safeParsePlainTime(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.PlainTime> {
    const result = _validatePlainTime(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainTime };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parsePlainTime(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.PlainTime {
    const result = safeParsePlainTime(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainTime> & {
    safeParse: typeof safeParsePlainTime;
    parse: typeof parsePlainTime;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParsePlainTime(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParsePlainTime,
    parse: parsePlainTime
};

export { _schema as PlainTime };
