// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParsePlainTime(value: unknown): ParseResult<Temporal.PlainTime> {
    {
        if (!(value instanceof Temporal.PlainTime)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainTime" });
        }
    }
    return { ok: true as const, value: value as Temporal.PlainTime };
}

export function parsePlainTime(value: unknown): Temporal.PlainTime {
    const result = safeParsePlainTime(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
