// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParsePlainYearMonth(value: unknown): ParseResult<Temporal.PlainYearMonth> {
    {
        if (!(value instanceof Temporal.PlainYearMonth)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainYearMonth" });
        }
    }
    return { ok: true as const, value: value as Temporal.PlainYearMonth };
}

export function parsePlainYearMonth(value: unknown): Temporal.PlainYearMonth {
    const result = safeParsePlainYearMonth(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
