// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _bound2 = Temporal.PlainDate.from("2020-01-01");

function _validatePlainDate(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.PlainDate> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Temporal.PlainDate)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainDate" };
        }
        const _iso1 = value.calendarId === "iso8601";
        if (!(_iso1 ? value.year > 2020 || value.year === 2020 && (value.month > 1 || value.month === 1 && value.day >= 1) : Temporal.PlainDate.compare(value, _bound2) >= 0)) {
            return { type: "leaf", code: issueCodes.TOO_DATED };
        }
        if (!(_iso1 ? value.year < 2020 || value.year === 2020 && (value.month < 1 || value.month === 1 && value.day <= 1) : Temporal.PlainDate.compare(value, _bound2) <= 0)) {
            return { type: "leaf", code: issueCodes.TOO_RECENT };
        }
    }
    return undefined;
}

function safeParsePlainDate(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.PlainDate> {
    const result = _validatePlainDate(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainDate };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parsePlainDate(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.PlainDate {
    const result = safeParsePlainDate(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainDate> & {
    safeParse: typeof safeParsePlainDate;
    parse: typeof parsePlainDate;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParsePlainDate(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParsePlainDate,
    parse: parsePlainDate
};

export { _schema as PlainDate };
