// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _shapeRecord6(_obj4: Record<string, unknown>): boolean {
    for (const _k5 in _obj4) {
        const _el1 = _obj4[_k5];
        if (!(typeof _el1 === "number" && !(Number.isNaN(_el1)))) {
            return false;
        }
    }
    return true;
}

function _slowRecord(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Record<PropertyKey, number>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(isPlainObject(value))) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Record" };
        }
        let _issue7: TreeNode | undefined;
        for (const _key8 in value) {
            let _value9 = (value as Record<PropertyKey, unknown>)[_key8];
            if (!(typeof _value9 === "number" && !(Number.isNaN(_value9)))) {
                _issue7 = addIssue(_issue7, { type: "nest", key: _key8, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
        }
        if (_issue7 !== undefined) {
            return _issue7;
        }
        return undefined;
    }
    return undefined;
}

function _validateRecord(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Record<PropertyKey, number>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (isPlainObject(value) && _shapeRecord6(value)) {
        return undefined;
    }
    return _slowRecord(value, options);
}

function safeParseRecord(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Record<PropertyKey, number>> {
    const result = _validateRecord(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Record<PropertyKey, number> };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseRecord(value: unknown, options?: {
    maxDepth?: number;
}): Record<PropertyKey, number> {
    const result = safeParseRecord(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Record<PropertyKey, number>> & {
    safeParse: typeof safeParseRecord;
    parse: typeof parseRecord;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseRecord(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseRecord,
    parse: parseRecord
};

export { _schema as Record };
