// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _refine1: (value: number) => boolean = (value) => value > 0;

function _validateRefine(value: unknown): InternalParseResult<number> {
    let _refineIssue2: TreeNode | undefined;
    let _refineValue3: unknown = value;
    let _refineModified4 = false;
    if (!(typeof _refineValue3 === "number" && !(Number.isNaN(_refineValue3)))) {
        _refineIssue2 = addIssue(_refineIssue2, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
    }
    else {
    }
    if (_refineIssue2 !== undefined) {
        return _refineIssue2;
    }
    else {
        if (!(_refine1(_refineValue3 as number))) {
            return { type: "leaf", code: "positive" as CustomIssueCode };
        }
        else {
            return { ok: true as const, value: _refineValue3 as number };
        }
    }
    return undefined;
}

function safeParseRefine(value: unknown): ParseResult<number> {
    const result = _validateRefine(value);
    if (result === undefined) {
        return { ok: true as const, value: value as number };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseRefine(value: unknown): number {
    const result = safeParseRefine(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, number> & {
    safeParse: typeof safeParseRefine;
    parse: typeof parseRefine;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseRefine(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseRefine,
    parse: parseRefine
};

export { _schema as Refine };
