// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _refine1: (value: number) => boolean = (value) => value > 0;

function _validateRefine(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<number> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    let _refineIssue2: TreeNode | undefined;
    let _refineValue3: unknown = value;
    let _refineModified4 = false;
    if (!(typeof _refineValue3 === "number" && !(Number.isNaN(_refineValue3)))) {
        _refineIssue2 = addIssue(_refineIssue2, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
    }
    else {
    }
    if (_refineIssue2 !== undefined) {
        return _refineIssue2;
    }
    else {
        if (!(_refine1(_refineValue3 as number))) {
            return { type: "leaf", code: "positive" as CustomIssueCode };
        }
        else {
            return { ok: true as const, value: _refineValue3 as number };
        }
    }
    return undefined;
}

function safeParseRefine(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<number> {
    const result = _validateRefine(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as number };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseRefine(value: unknown, options?: {
    maxDepth?: number;
}): number {
    const result = safeParseRefine(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, number> & {
    safeParse: typeof safeParseRefine;
    parse: typeof parseRefine;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, number>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateRefine(value);
            if (result === undefined) {
                return { value: value as number };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: number;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseRefine,
    parse: parseRefine
};

export { _schema as Refine };
