// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

const _refine1: (value: number) => boolean = (value) => value > 0;

export function safeParseRefine(value: unknown): ParseResult<number> {
    let _refineIssue2: TreeNode | undefined;
    let _refineValue3: unknown = value;
    let _refineModified4 = false;
    if (!(typeof _refineValue3 === "number" && !(Number.isNaN(_refineValue3)))) {
        _refineIssue2 = addIssue(_refineIssue2, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
    }
    else {
    }
    if (_refineIssue2 !== undefined) {
        return new ParseErrorResult(_refineIssue2);
    }
    else {
        if (!(_refine1(_refineValue3 as number))) {
            return new ParseErrorResult({ type: "leaf", code: "positive" as CustomIssueCode });
        }
        else {
            return { ok: true as const, value: _refineValue3 as number };
        }
    }
    return { ok: true as const, value: value as number };
}

export function parseRefine(value: unknown): number {
    const result = safeParseRefine(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
