// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _shapeSet5(_set4: Set<unknown>): boolean {
    for (const _el1 of _set4) {
        if (!(typeof _el1 === "string")) {
            return false;
        }
    }
    return true;
}

function _slowSet(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Set<string>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Set)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Set" };
        }
        let _issue6: TreeNode | undefined;
        let _index7 = 0;
        for (const _element8 of value) {
            if (!(typeof _element8 === "string")) {
                _issue6 = addIssue(_issue6, { type: "nest", key: _index7, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
            _index7++;
        }
        if (_issue6 !== undefined) {
            return _issue6;
        }
        return undefined;
    }
    return undefined;
}

function _validateSet(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Set<string>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value instanceof Set && _shapeSet5(value)) {
        return undefined;
    }
    return _slowSet(value, options);
}

function safeParseSet(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Set<string>> {
    const result = _validateSet(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Set<string> };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseSet(value: unknown, options?: {
    maxDepth?: number;
}): Set<string> {
    const result = safeParseSet(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Set<string>> & {
    safeParse: typeof safeParseSet;
    parse: typeof parseSet;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseSet(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseSet,
    parse: parseSet
};

export { _schema as Set };
