// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

function _shapeSet5(_set4: Set<unknown>): boolean {
    for (const _el1 of _set4) {
        if (!(typeof _el1 === "string")) {
            return false;
        }
    }
    return true;
}

function _slowSet(value: unknown): ParseResult<Set<string>> {
    {
        if (!(value instanceof Set)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Set" });
        }
        let _issue6: TreeNode | undefined;
        let _index7 = 0;
        for (const _element8 of value) {
            if (!(typeof _element8 === "string")) {
                _issue6 = addIssue(_issue6, { type: "nest", key: _index7, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
            _index7++;
        }
        if (_issue6 !== undefined) {
            return new ParseErrorResult(_issue6);
        }
        return { ok: true as const, value: value as Set<string> };
    }
    return { ok: true as const, value: value as Set<string> };
}

export function safeParseSet(value: unknown): ParseResult<Set<string>> {
    if (value instanceof Set && _shapeSet5(value)) {
        return { ok: true as const, value: value as Set<string> };
    }
    return _slowSet(value);
}

export function parseSet(value: unknown): Set<string> {
    const result = safeParseSet(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
