// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

function _shapeSet5(_set4: Set<unknown>): boolean {
    for (const _el1 of _set4) {
        if (!(typeof _el1 === "string")) {
            return false;
        }
    }
    return true;
}

const _default0 = deepFreeze(structuredClone("x"));

function _slowSetDefault(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Set<string>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Set)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Set" };
        }
        let _issue6: TreeNode | undefined;
        let _newSet7: Set<unknown> | undefined;
        let _index8 = 0;
        for (const _element9 of value) {
            let _modifiedElement10: unknown = _element9;
            let _elementModified11 = false;
            let _beforeIssue12: TreeNode | undefined = _issue6;
            if (_element9 === undefined) {
                _modifiedElement10 = _default0;
                _elementModified11 = true;
            }
            else {
                if (!(typeof _element9 === "string")) {
                    _issue6 = addIssue(_issue6, { type: "nest", key: _index8, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                }
                else {
                }
            }
            if (_beforeIssue12 !== _issue6) {
                if (_newSet7 !== undefined) {
                    _newSet7.add(_element9);
                }
            }
            else {
                if (_elementModified11) {
                    if (_newSet7 === undefined) {
                        _newSet7 = new Set();
                        let _prevIndex14 = 0;
                        for (const _prev13 of value) {
                            if (_prevIndex14 >= _index8) {
                                break;
                            }
                            _newSet7.add(_prev13);
                            _prevIndex14++;
                        }
                    }
                    _newSet7.add(_modifiedElement10);
                }
                else {
                    if (_newSet7 !== undefined) {
                        _newSet7.add(_element9);
                    }
                }
            }
            _index8++;
        }
        if (_issue6 !== undefined) {
            return _issue6;
        }
        if (_newSet7 !== undefined) {
            if (_newSet7.size !== _index8) {
                return { type: "leaf", code: issueCodes.DUPLICATE_KEY };
            }
        }
        if (_newSet7 !== undefined) {
            return { ok: true as const, value: _newSet7 as Set<string> };
        }
        return undefined;
    }
    return undefined;
}

function _validateSetDefault(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Set<string>> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value instanceof Set && _shapeSet5(value)) {
        return undefined;
    }
    return _slowSetDefault(value, options);
}

function safeParseSetDefault(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Set<string>> {
    const result = _validateSetDefault(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Set<string> };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseSetDefault(value: unknown, options?: {
    maxDepth?: number;
}): Set<string> {
    const result = safeParseSetDefault(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Set<string>> & {
    safeParse: typeof safeParseSetDefault;
    parse: typeof parseSetDefault;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseSetDefault(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseSetDefault,
    parse: parseSetDefault
};

export { _schema as SetDefault };
