// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

const _regex1 = new RegExp("^[a-z]+$", "");

export function safeParseStringConstrained(value: unknown): ParseResult<string> {
    {
        if (!(typeof value === "string")) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
        }
        if (!(value.length >= 1)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.TOO_SHORT });
        }
        if (!(value.length <= 10)) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.TOO_LONG });
        }
        if (!(_regex1.test(value))) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.DOES_NOT_MATCH_REGEX });
        }
    }
    return { ok: true as const, value: value as string };
}

export function parseStringConstrained(value: unknown): string {
    const result = safeParseStringConstrained(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
