// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _regex1 = new RegExp("^[a-z]+$", "");

function _validateStringConstrained(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(typeof value === "string")) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" };
        }
        if (!(value.length >= 1)) {
            return { type: "leaf", code: issueCodes.TOO_SHORT };
        }
        if (!(value.length <= 10)) {
            return { type: "leaf", code: issueCodes.TOO_LONG };
        }
        if (!(_regex1.test(value))) {
            return { type: "leaf", code: issueCodes.DOES_NOT_MATCH_REGEX };
        }
    }
    return undefined;
}

function safeParseStringConstrained(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<string> {
    const result = _validateStringConstrained(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as string };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseStringConstrained(value: unknown, options?: {
    maxDepth?: number;
}): string {
    const result = safeParseStringConstrained(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string> & {
    safeParse: typeof safeParseStringConstrained;
    parse: typeof parseStringConstrained;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, string>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateStringConstrained(value);
            if (result === undefined) {
                return { value: value as string };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: string;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseStringConstrained,
    parse: parseStringConstrained
};

export { _schema as StringConstrained };
