// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _regex1 = new RegExp("^[a-z]+$", "");

function _validateStringConstrained(value: unknown): InternalParseResult<string> {
    {
        if (!(typeof value === "string")) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" };
        }
        if (!(value.length >= 1)) {
            return { type: "leaf", code: issueCodes.TOO_SHORT };
        }
        if (!(value.length <= 10)) {
            return { type: "leaf", code: issueCodes.TOO_LONG };
        }
        if (!(_regex1.test(value))) {
            return { type: "leaf", code: issueCodes.DOES_NOT_MATCH_REGEX };
        }
    }
    return undefined;
}

function safeParseStringConstrained(value: unknown): ParseResult<string> {
    const result = _validateStringConstrained(value);
    if (result === undefined) {
        return { ok: true as const, value: value as string };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseStringConstrained(value: unknown): string {
    const result = safeParseStringConstrained(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string> & {
    safeParse: typeof safeParseStringConstrained;
    parse: typeof parseStringConstrained;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseStringConstrained(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseStringConstrained,
    parse: parseStringConstrained
};

export { _schema as StringConstrained };
