// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseStringPlain(value: unknown): ParseResult<string> {
    {
        if (!(typeof value === "string")) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
        }
    }
    return { ok: true as const, value: value as string };
}

export function parseStringPlain(value: unknown): string {
    const result = safeParseStringPlain(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
