// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateSymbol(value: unknown): InternalParseResult<symbol> {
    if (!(typeof value === "symbol")) {
        return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Symbol" };
    }
    return undefined;
}

function safeParseSymbol(value: unknown): ParseResult<symbol> {
    const result = _validateSymbol(value);
    if (result === undefined) {
        return { ok: true as const, value: value as symbol };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseSymbol(value: unknown): symbol {
    const result = safeParseSymbol(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, symbol> & {
    safeParse: typeof safeParseSymbol;
    parse: typeof parseSymbol;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseSymbol(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseSymbol,
    parse: parseSymbol
};

export { _schema as Symbol };
