// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseSymbol(value: unknown): ParseResult<symbol> {
    if (!(typeof value === "symbol")) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Symbol" });
    }
    return { ok: true as const, value: value as symbol };
}

export function parseSymbol(value: unknown): symbol {
    const result = safeParseSymbol(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
