// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function deepFreeze<T>(value: T): T {
    if (value === null || typeof value !== "object" || Object.isFrozen(value)) {
        return value;
    }
    Object.freeze(value);
    for (const key of Reflect.ownKeys(value)) {
        deepFreeze((value as Record<PropertyKey, unknown>)[key]);
    }
    return value;
}

const _default0 = deepFreeze(Temporal.PlainDate.from("2020-01-01"));

function _validateTemporalDefault(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.PlainDate> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (value === undefined) {
        return { ok: true as const, value: _default0 as Temporal.PlainDate };
    }
    {
        if (!(value instanceof Temporal.PlainDate)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.PlainDate" };
        }
    }
    return undefined;
}

function safeParseTemporalDefault(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.PlainDate> {
    const result = _validateTemporalDefault(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.PlainDate };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseTemporalDefault(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.PlainDate {
    const result = safeParseTemporalDefault(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.PlainDate> & {
    safeParse: typeof safeParseTemporalDefault;
    parse: typeof parseTemporalDefault;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseTemporalDefault(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseTemporalDefault,
    parse: parseTemporalDefault
};

export { _schema as TemporalDefault };
