// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _slowTuple(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<[
    string,
    number,
    123n
]> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(Array.isArray(value))) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" };
        }
        let _issue1: TreeNode | undefined;
        _labelTuple2: {
            if (value.length > 3) {
                _issue1 = addIssue(_issue1, { type: "leaf", code: issueCodes.TOO_LONG });
                break _labelTuple2;
            }
            if (value.length < 3) {
                _issue1 = addIssue(_issue1, { type: "leaf", code: issueCodes.TOO_SHORT });
                break _labelTuple2;
            }
            let _value3 = value[0];
            if (!(typeof _value3 === "string")) {
                _issue1 = addIssue(_issue1, { type: "nest", key: 0, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
            let _value4 = value[1];
            if (!(typeof _value4 === "number" && !(Number.isNaN(_value4)))) {
                _issue1 = addIssue(_issue1, { type: "nest", key: 1, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
            let _value5 = value[2];
            if (!(_value5 === 123n)) {
                _issue1 = addIssue(_issue1, { type: "nest", key: 2, child: { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "123n" } });
            }
        }
        if (_issue1 !== undefined) {
            return _issue1;
        }
        return undefined;
    }
    return undefined;
}

function _validateTuple(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<[
    string,
    number,
    123n
]> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (Array.isArray(value) && value.length === 3 && typeof value[0] === "string" && (typeof value[1] === "number" && !(Number.isNaN(value[1]))) && value[2] === 123n) {
        return undefined;
    }
    return _slowTuple(value, options);
}

function safeParseTuple(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<[
    string,
    number,
    123n
]> {
    const result = _validateTuple(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as [
                string,
                number,
                123n
            ] };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseTuple(value: unknown, options?: {
    maxDepth?: number;
}): [
    string,
    number,
    123n
] {
    const result = safeParseTuple(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, [
    string,
    number,
    123n
]> & {
    safeParse: typeof safeParseTuple;
    parse: typeof parseTuple;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, [
        string,
        number,
        123n
    ]>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateTuple(value);
            if (result === undefined) {
                return { value: value as [
                        string,
                        number,
                        123n
                    ] };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: [
                            string,
                            number,
                            123n
                        ];
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseTuple,
    parse: parseTuple
};

export { _schema as Tuple };
