// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

function _slowTuple(value: unknown): ParseResult<[
    string,
    number,
    123n
]> {
    {
        if (!(Array.isArray(value))) {
            return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_TYPE, expected: "array" });
        }
        let _issue1: TreeNode | undefined;
        _labelTuple2: {
            if (value.length > 3) {
                _issue1 = addIssue(_issue1, { type: "leaf", code: issueCodes.TOO_LONG });
                break _labelTuple2;
            }
            if (value.length < 3) {
                _issue1 = addIssue(_issue1, { type: "leaf", code: issueCodes.TOO_SHORT });
                break _labelTuple2;
            }
            let _value3 = value[0];
            if (!(typeof _value3 === "string")) {
                _issue1 = addIssue(_issue1, { type: "nest", key: 0, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
            }
            else {
            }
            let _value4 = value[1];
            if (!(typeof _value4 === "number" && !(Number.isNaN(_value4)))) {
                _issue1 = addIssue(_issue1, { type: "nest", key: 1, child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
            let _value5 = value[2];
            if (!(_value5 === 123n)) {
                _issue1 = addIssue(_issue1, { type: "nest", key: 2, child: { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "123n" } });
            }
        }
        if (_issue1 !== undefined) {
            return new ParseErrorResult(_issue1);
        }
        return { ok: true as const, value: value as [
                string,
                number,
                123n
            ] };
    }
    return { ok: true as const, value: value as [
            string,
            number,
            123n
        ] };
}

export function safeParseTuple(value: unknown): ParseResult<[
    string,
    number,
    123n
]> {
    if (Array.isArray(value) && value.length === 3 && typeof value[0] === "string" && (typeof value[1] === "number" && !(Number.isNaN(value[1]))) && value[2] === 123n) {
        return { ok: true as const, value: value as [
                string,
                number,
                123n
            ] };
    }
    return _slowTuple(value);
}

export function parseTuple(value: unknown): [
    string,
    number,
    123n
] {
    const result = safeParseTuple(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
