// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateUndefined(value: unknown): InternalParseResult<undefined> {
    if (!(value === undefined)) {
        return { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "undefined" };
    }
    return undefined;
}

function safeParseUndefined(value: unknown): ParseResult<undefined> {
    const result = _validateUndefined(value);
    if (result === undefined) {
        return { ok: true as const, value: value as undefined };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseUndefined(value: unknown): undefined {
    const result = safeParseUndefined(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, undefined> & {
    safeParse: typeof safeParseUndefined;
    parse: typeof parseUndefined;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseUndefined(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseUndefined,
    parse: parseUndefined
};

export { _schema as Undefined };
