// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

const _enum1 = new Set<unknown>(["a", "b", "c"]);

function _slowUnionLiteral(value: unknown): InternalParseResult<"a" | "b" | "c"> {
    if (!(_enum1.has(value))) {
        return { type: "leaf", code: issueCodes.INVALID_ENUM_VALUE, expected: ["'a'", "'b'", "'c'"] };
    }
    return undefined;
}

function _validateUnionLiteral(value: unknown): InternalParseResult<"a" | "b" | "c"> {
    if (value === "a" || value === "b" || value === "c") {
        return undefined;
    }
    return _slowUnionLiteral(value);
}

function safeParseUnionLiteral(value: unknown): ParseResult<"a" | "b" | "c"> {
    const result = _validateUnionLiteral(value);
    if (result === undefined) {
        return { ok: true as const, value: value as "a" | "b" | "c" };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseUnionLiteral(value: unknown): "a" | "b" | "c" {
    const result = safeParseUnionLiteral(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, "a" | "b" | "c"> & {
    safeParse: typeof safeParseUnionLiteral;
    parse: typeof parseUnionLiteral;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseUnionLiteral(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseUnionLiteral,
    parse: parseUnionLiteral
};

export { _schema as UnionLiteral };
