// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _slowUnionMixed(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string | number> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (typeof value === "string" || typeof value === "number" && !(Number.isNaN(value))) {
        return undefined;
    }
    {
        let _success1 = false;
        let _issue2: TreeNode | undefined;
        if (!(_success1)) {
            {
                let _memberIssue3: TreeNode | undefined;
                if (!(typeof value === "string")) {
                    _memberIssue3 = addIssue(_memberIssue3, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
                }
                else {
                }
                if (_memberIssue3 === undefined) {
                    _success1 = true;
                }
                else {
                    _issue2 = addIssue(_issue2, _memberIssue3);
                }
            }
        }
        if (!(_success1)) {
            {
                let _memberIssue4: TreeNode | undefined;
                if (!(typeof value === "number" && !(Number.isNaN(value)))) {
                    _memberIssue4 = addIssue(_memberIssue4, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
                }
                else {
                }
                if (_memberIssue4 === undefined) {
                    _success1 = true;
                }
                else {
                    _issue2 = addIssue(_issue2, _memberIssue4);
                }
            }
        }
        if (_success1) {
            return undefined;
        }
        else {
            return _issue2!;
        }
    }
    return undefined;
}

function _validateUnionMixed(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<string | number> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (typeof value === "string" || typeof value === "number" && !(Number.isNaN(value))) {
        return undefined;
    }
    return _slowUnionMixed(value, options);
}

function safeParseUnionMixed(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<string | number> {
    const result = _validateUnionMixed(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as string | number };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseUnionMixed(value: unknown, options?: {
    maxDepth?: number;
}): string | number {
    const result = safeParseUnionMixed(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, string | number> & {
    safeParse: typeof safeParseUnionMixed;
    parse: typeof parseUnionMixed;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseUnionMixed(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseUnionMixed,
    parse: parseUnionMixed
};

export { _schema as UnionMixed };
