// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

const _enum1 = new Set<unknown>(["a", "b", "c"]);

function _slowUnionLiteral(value: unknown): ParseResult<"a" | "b" | "c"> {
    if (!(_enum1.has(value))) {
        return new ParseErrorResult({ type: "leaf", code: issueCodes.INVALID_ENUM_VALUE, expected: ["'a'", "'b'", "'c'"] });
    }
    return { ok: true as const, value: value as "a" | "b" | "c" };
}

export function safeParseUnionLiteral(value: unknown): ParseResult<"a" | "b" | "c"> {
    if (value === "a" || value === "b" || value === "c") {
        return { ok: true as const, value: value as "a" | "b" | "c" };
    }
    return _slowUnionLiteral(value);
}

export function parseUnionLiteral(value: unknown): "a" | "b" | "c" {
    const result = safeParseUnionLiteral(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
