// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

function _slowUnionMixed(value: unknown): ParseResult<string | number> {
    if (typeof value === "string" || typeof value === "number" && !(Number.isNaN(value))) {
        return { ok: true as const, value: value as string | number };
    }
    {
        let _success1 = false;
        let _issue2: TreeNode | undefined;
        if (!(_success1)) {
            {
                let _memberIssue3: TreeNode | undefined;
                if (!(typeof value === "string")) {
                    _memberIssue3 = addIssue(_memberIssue3, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" });
                }
                else {
                }
                if (_memberIssue3 === undefined) {
                    _success1 = true;
                }
                else {
                    _issue2 = addIssue(_issue2, _memberIssue3);
                }
            }
        }
        if (!(_success1)) {
            {
                let _memberIssue4: TreeNode | undefined;
                if (!(typeof value === "number" && !(Number.isNaN(value)))) {
                    _memberIssue4 = addIssue(_memberIssue4, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" });
                }
                else {
                }
                if (_memberIssue4 === undefined) {
                    _success1 = true;
                }
                else {
                    _issue2 = addIssue(_issue2, _memberIssue4);
                }
            }
        }
        if (_success1) {
            return { ok: true as const, value: value as string | number };
        }
        else {
            return new ParseErrorResult(_issue2!);
        }
    }
    return { ok: true as const, value: value as string | number };
}

export function safeParseUnionMixed(value: unknown): ParseResult<string | number> {
    if (typeof value === "string" || typeof value === "number" && !(Number.isNaN(value))) {
        return { ok: true as const, value: value as string | number };
    }
    return _slowUnionMixed(value);
}

export function parseUnionMixed(value: unknown): string | number {
    const result = safeParseUnionMixed(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
