// Auto-generated by paseri-compiler. Do not edit.

import { addIssue, isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

// biome-ignore-all lint/correctness/noUnusedVariables: consumed at codegen time, not via import.
// Incidental utilities spliced into compiled validators. This file is the source of truth; `deno task
// generate_runtime` embeds its verbatim text into `runtime.gen.ts`, and `selectRuntimeStatements()` in
// `toSource.ts` parses that string at codegen time, including only the declarations each schema needs. Re-run the
// task after editing this file. The result/issue/message contract is NOT here — generated code imports it from
// `@paseri/paseri/internal` so it reuses the runtime's exact machinery (see `toSource.ts`).
// Mirrors paseri-lib's `utils.ts` isPlainObject exactly — the compiled object/record predicate must accept and reject
// the same values as the runtime. Keep these in lockstep (the `constructor` and `Array.isArray` branches both matter).
function isPlainObject(value: unknown): value is Record<PropertyKey, unknown> {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return false;
    }
    if (value.constructor === Object) {
        return true;
    }
    if (value.constructor === undefined) {
        return Object.getPrototypeOf(value) === null;
    }
    if (!Object.hasOwn(value, "constructor")) {
        return false;
    }
    return Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null;
}

function _objectIssues16(_val6: unknown): TreeNode | undefined {
    let _issue7: TreeNode | undefined;
    if (!(isPlainObject(_val6))) {
        _issue7 = addIssue(_issue7, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" });
    }
    else {
        let _issue8: TreeNode | undefined;
        let _value9: unknown;
        const _has10 = "kind" in _val6;
        if (_has10) {
            _value9 = (_val6 as Record<PropertyKey, unknown>)["kind"];
            if (!(_value9 === "b")) {
                _issue8 = addIssue(_issue8, { type: "nest", key: "kind", child: { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "'b'" } });
            }
        }
        let _value11: unknown;
        const _has12 = "value" in _val6;
        if (_has12) {
            _value11 = (_val6 as Record<PropertyKey, unknown>)["value"];
            if (!(typeof _value11 === "number" && !(Number.isNaN(_value11)))) {
                _issue8 = addIssue(_issue8, { type: "nest", key: "value", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "number" } });
            }
            else {
            }
        }
        if (!(_has10)) {
            _issue8 = addIssue(_issue8, { type: "nest", key: "kind", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
        if (!(_has12)) {
            _issue8 = addIssue(_issue8, { type: "nest", key: "value", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
        }
        let _count14 = 0;
        for (const _k15 in _val6) {
            _count14++;
        }
        if (_count14 !== 2 || !(_has10) || !(_has12)) {
            for (const _key13 in _val6) {
                if (!(_key13 === "kind" || _key13 === "value")) {
                    _issue8 = addIssue(_issue8, { type: "nest", key: _key13, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
                }
            }
        }
        if (_issue8 !== undefined) {
            _issue7 = addIssue(_issue7, _issue8);
        }
    }
    return _issue7;
}

const _refine1: (value: {
    "kind": "a";
    "value": string;
}) => boolean = (data) => data.value.length > 0;

function _slowUnionDiscriminatedRefine(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "kind": "a";
    "value": string;
} | {
    "kind": "b";
    "value": number;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(isPlainObject(value))) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" };
        }
        if (value["kind"] === "a") {
            let _refineIssue18: TreeNode | undefined;
            let _refineValue19: unknown = value;
            let _refineModified20 = false;
            if (!(isPlainObject(_refineValue19))) {
                _refineIssue18 = addIssue(_refineIssue18, { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "object" });
            }
            else {
                let _issue21: TreeNode | undefined;
                let _value22: unknown;
                const _has23 = "kind" in _refineValue19;
                if (_has23) {
                    _value22 = (_refineValue19 as Record<PropertyKey, unknown>)["kind"];
                    if (!(_value22 === "a")) {
                        _issue21 = addIssue(_issue21, { type: "nest", key: "kind", child: { type: "leaf", code: issueCodes.INVALID_VALUE, expected: "'a'" } });
                    }
                }
                let _value24: unknown;
                const _has25 = "value" in _refineValue19;
                if (_has25) {
                    _value24 = (_refineValue19 as Record<PropertyKey, unknown>)["value"];
                    if (!(typeof _value24 === "string")) {
                        _issue21 = addIssue(_issue21, { type: "nest", key: "value", child: { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "string" } });
                    }
                    else {
                    }
                }
                if (!(_has23)) {
                    _issue21 = addIssue(_issue21, { type: "nest", key: "kind", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
                }
                if (!(_has25)) {
                    _issue21 = addIssue(_issue21, { type: "nest", key: "value", child: { type: "leaf", code: issueCodes.MISSING_VALUE } });
                }
                let _count27 = 0;
                for (const _k28 in _refineValue19) {
                    _count27++;
                }
                if (_count27 !== 2 || !(_has23) || !(_has25)) {
                    for (const _key26 in _refineValue19) {
                        if (!(_key26 === "kind" || _key26 === "value")) {
                            _issue21 = addIssue(_issue21, { type: "nest", key: _key26, child: { type: "leaf", code: issueCodes.UNRECOGNIZED_KEY } });
                        }
                    }
                }
                if (_issue21 !== undefined) {
                    _refineIssue18 = addIssue(_refineIssue18, _issue21);
                }
            }
            if (_refineIssue18 !== undefined) {
                return _refineIssue18;
            }
            else {
                if (!(_refine1(_refineValue19 as {
                    "kind": "a";
                    "value": string;
                }))) {
                    return { type: "leaf", code: "non_empty" as CustomIssueCode };
                }
                else {
                    return { ok: true as const, value: _refineValue19 as {
                            "kind": "a";
                            "value": string;
                        } | {
                            "kind": "b";
                            "value": number;
                        } };
                }
            }
        }
        else {
            if (value["kind"] === "b") {
                const _childIssue17 = _objectIssues16(value);
                if (_childIssue17 !== undefined) {
                    return _childIssue17;
                }
                return undefined;
            }
            else {
                return { type: "leaf", code: issueCodes.INVALID_DISCRIMINATOR_VALUE, expected: ["'a'", "'b'"] };
            }
        }
    }
    return undefined;
}

function _validateUnionDiscriminatedRefine(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<{
    "kind": "a";
    "value": string;
} | {
    "kind": "b";
    "value": number;
}> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    if (typeof value === "object" && value !== null) {
        switch ((value as Record<PropertyKey, unknown>)["kind"]) {
            case "a":
                if (isPlainObject(value) && (value as Record<PropertyKey, unknown>)["kind"] === "a" && typeof (value as Record<PropertyKey, unknown>)["value"] === "string" && _refine1(value as {
                    "kind": "a";
                    "value": string;
                })) {
                    let _count2 = 0;
                    for (const _k3 in value) {
                        _count2++;
                    }
                    if (_count2 > 2) {
                        return _slowUnionDiscriminatedRefine(value, options);
                    }
                    return undefined;
                }
                break;
            case "b":
                if (isPlainObject(value) && (value as Record<PropertyKey, unknown>)["kind"] === "b" && (typeof (value as Record<PropertyKey, unknown>)["value"] === "number" && !(Number.isNaN((value as Record<PropertyKey, unknown>)["value"])))) {
                    let _count4 = 0;
                    for (const _k5 in value) {
                        _count4++;
                    }
                    if (_count4 > 2) {
                        return _slowUnionDiscriminatedRefine(value, options);
                    }
                    return undefined;
                }
                break;
        }
    }
    return _slowUnionDiscriminatedRefine(value, options);
}

function safeParseUnionDiscriminatedRefine(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<{
    "kind": "a";
    "value": string;
} | {
    "kind": "b";
    "value": number;
}> {
    const result = _validateUnionDiscriminatedRefine(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as {
                "kind": "a";
                "value": string;
            } | {
                "kind": "b";
                "value": number;
            } };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseUnionDiscriminatedRefine(value: unknown, options?: {
    maxDepth?: number;
}): {
    "kind": "a";
    "value": string;
} | {
    "kind": "b";
    "value": number;
} {
    const result = safeParseUnionDiscriminatedRefine(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, {
    "kind": "a";
    "value": string;
} | {
    "kind": "b";
    "value": number;
}> & {
    safeParse: typeof safeParseUnionDiscriminatedRefine;
    parse: typeof parseUnionDiscriminatedRefine;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, {
        "kind": "a";
        "value": string;
    } | {
        "kind": "b";
        "value": number;
    }>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateUnionDiscriminatedRefine(value);
            if (result === undefined) {
                return { value: value as {
                        "kind": "a";
                        "value": string;
                    } | {
                        "kind": "b";
                        "value": number;
                    } };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: {
                            "kind": "a";
                            "value": string;
                        } | {
                            "kind": "b";
                            "value": number;
                        };
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseUnionDiscriminatedRefine,
    parse: parseUnionDiscriminatedRefine
};

export { _schema as UnionDiscriminatedRefine };
