// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateUnknown(value: unknown): InternalParseResult<unknown> {
    return undefined;
}

function safeParseUnknown(value: unknown): ParseResult<unknown> {
    const result = _validateUnknown(value);
    if (result === undefined) {
        return { ok: true as const, value: value as unknown };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseUnknown(value: unknown): unknown {
    const result = safeParseUnknown(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, unknown> & {
    safeParse: typeof safeParseUnknown;
    parse: typeof parseUnknown;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseUnknown(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseUnknown,
    parse: parseUnknown
};

export { _schema as Unknown };
