// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateUnknown(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<unknown> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    return undefined;
}

function safeParseUnknown(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<unknown> {
    const result = _validateUnknown(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as unknown };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseUnknown(value: unknown, options?: {
    maxDepth?: number;
}): unknown {
    const result = safeParseUnknown(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, unknown> & {
    safeParse: typeof safeParseUnknown;
    parse: typeof parseUnknown;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, unknown>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateUnknown(value);
            if (result === undefined) {
                return { value: value as unknown };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: unknown;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseUnknown,
    parse: parseUnknown
};

export { _schema as Unknown };
