// Auto-generated by paseri-compiler. Do not edit.

import { issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type ParseResult, type TreeNode } from '@paseri/paseri/internal';

export function safeParseUnknown(value: unknown): ParseResult<unknown> {
    return { ok: true as const, value: value as unknown };
}

export function parseUnknown(value: unknown): unknown {
    const result = safeParseUnknown(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}
