// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateZonedDateTime(value: unknown, options?: {
    maxDepth?: number;
}): InternalParseResult<Temporal.ZonedDateTime> {
    const maxDepth: number = options?.maxDepth ?? 1000;
    if (!(Number.isInteger(maxDepth)) || maxDepth < 1) {
        throw new Error("maxDepth must be a positive integer.");
    }
    {
        if (!(value instanceof Temporal.ZonedDateTime)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.ZonedDateTime" };
        }
    }
    return undefined;
}

function safeParseZonedDateTime(value: unknown, options?: {
    maxDepth?: number;
}): ParseResult<Temporal.ZonedDateTime> {
    const result = _validateZonedDateTime(value, options);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.ZonedDateTime };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseZonedDateTime(value: unknown, options?: {
    maxDepth?: number;
}): Temporal.ZonedDateTime {
    const result = safeParseZonedDateTime(value, options);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.ZonedDateTime> & {
    safeParse: typeof safeParseZonedDateTime;
    parse: typeof parseZonedDateTime;
} = {
    "~standard": Object.freeze<StandardSchemaV1.Props<unknown, Temporal.ZonedDateTime>>({
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = _validateZonedDateTime(value);
            if (result === undefined) {
                return { value: value as Temporal.ZonedDateTime };
            }
            if ((result as {
                ok?: unknown;
            }).ok === true) {
                return { value: (result as {
                        ok: true;
                        value: Temporal.ZonedDateTime;
                    }).value };
            }
            return { issues: new ParseErrorResult(result as TreeNode).messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    }),
    safeParse: safeParseZonedDateTime,
    parse: parseZonedDateTime
};

export { _schema as ZonedDateTime };
