// Auto-generated by paseri-compiler. Do not edit.

import { isParseSuccess, issueCodes, ParseErrorResult, PaseriError, type CustomIssueCode, type InternalParseResult, type ParseResult, type StandardSchemaV1, type Translations, type TreeNode } from '@paseri/paseri/internal';

function _validateZonedDateTime(value: unknown): InternalParseResult<Temporal.ZonedDateTime> {
    {
        if (!(value instanceof Temporal.ZonedDateTime)) {
            return { type: "leaf", code: issueCodes.INVALID_TYPE, expected: "Temporal.ZonedDateTime" };
        }
    }
    return undefined;
}

function safeParseZonedDateTime(value: unknown): ParseResult<Temporal.ZonedDateTime> {
    const result = _validateZonedDateTime(value);
    if (result === undefined) {
        return { ok: true as const, value: value as Temporal.ZonedDateTime };
    }
    if (isParseSuccess(result)) {
        return result;
    }
    return new ParseErrorResult(result);
}

function parseZonedDateTime(value: unknown): Temporal.ZonedDateTime {
    const result = safeParseZonedDateTime(value);
    if (result.ok) {
        return result.value;
    }
    throw new PaseriError(result.issue);
}

const _schema: StandardSchemaV1<unknown, Temporal.ZonedDateTime> & {
    safeParse: typeof safeParseZonedDateTime;
    parse: typeof parseZonedDateTime;
} = {
    "~standard": {
        version: 1,
        vendor: "paseri",
        validate(value, options?) {
            const result = safeParseZonedDateTime(value);
            if (result.ok) {
                return { value: result.value };
            }
            return { issues: result.messages(options?.libraryOptions?.locale as Translations | undefined) };
        }
    },
    safeParse: safeParseZonedDateTime,
    parse: parseZonedDateTime
};

export { _schema as ZonedDateTime };
