name: Commit lint

on: workflow_call

jobs:
  unit:
    name: Commit lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v2

      - name: Get pnpm store directory
        id: deno-cache
        shell: bash
        run: |
          echo "DENO_DIR=$(deno info | grep DENO_DIR | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' | cut -d ':' -f 2 | xargs)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup Deno cache
        with:
          path: ${{ steps.deno-cache.outputs.DENO_DIR }}
          key: ${{ runner.os }}-deno-cache
          restore-keys: |
            ${{ runner.os }}-deno-cache

      - name: Commit lint
        id: commitlint
        run: |
          deno task commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
