name: Pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  commitlint:
    uses: ./.github/workflows/commitlint.yml

  test:
    needs: [lint, commitlint]
    uses: ./.github/workflows/test.yml
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
