name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/test.yml
    with:
      use_cache: false

  bundle-size:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/bundle-size.yml

  badges:
    needs: [test, bundle-size]
    runs-on: ubuntu-latest
    environment: badges
    permissions: {}
    steps:
      - name: Update paseri-lib coverage badge
        uses: schneegans/dynamic-badges-action@0e50b8bad39e7e1afd3e4e9c2b7dd145fad07501 # v1.8.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 80548a1b87f9f00fe1ae426ca6a2a517
          filename: vbudovski_paseri_main-coverage.svg
          label: coverage
          message: ${{ needs.test.outputs.lib_coverage }}%
          valColorRange: ${{ needs.test.outputs.lib_coverage }}
          minColorRange: 50
          maxColorRange: 90

      - name: Update paseri-compiler coverage badge
        uses: schneegans/dynamic-badges-action@0e50b8bad39e7e1afd3e4e9c2b7dd145fad07501 # v1.8.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 80548a1b87f9f00fe1ae426ca6a2a517
          filename: vbudovski_paseri-compiler_main-coverage.svg
          label: coverage
          message: ${{ needs.test.outputs.compiler_coverage }}%
          valColorRange: ${{ needs.test.outputs.compiler_coverage }}
          minColorRange: 50
          maxColorRange: 90

      - name: Update paseri-vite-plugin coverage badge
        uses: schneegans/dynamic-badges-action@0e50b8bad39e7e1afd3e4e9c2b7dd145fad07501 # v1.8.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 80548a1b87f9f00fe1ae426ca6a2a517
          filename: vbudovski_paseri-vite-plugin_main-coverage.svg
          label: coverage
          message: ${{ needs.test.outputs.vite_plugin_coverage }}%
          valColorRange: ${{ needs.test.outputs.vite_plugin_coverage }}
          minColorRange: 50
          maxColorRange: 90

      - name: Update bundle size badge
        uses: schneegans/dynamic-badges-action@0e50b8bad39e7e1afd3e4e9c2b7dd145fad07501 # v1.8.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 80548a1b87f9f00fe1ae426ca6a2a517
          filename: vbudovski_paseri_main-bundlesize.svg
          label: minzip
          message: ${{ needs.bundle-size.outputs.bundle_size }}
          color: blue

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write # Required for pushing tags and creating draft GitHub releases.
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: "^2.9.0"

      - run: deno publish

      - name: Tag and release per package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: deno task post-publish
